// <copyright file="SourceCodeTools.cs" company="VoxelGame">
//     MIT License
//     For full license see the repository.
// </copyright>
// <author>jeanpmathes</author>

using System;
using System.Text;
using Microsoft.CodeAnalysis;

namespace VoxelGame.SourceGenerators.Utilities;

/// <summary>
///     Tools to help with generating source code.
/// </summary>
public static class SourceCodeTools
{
    /// <summary>
    ///     The preferred symbol display format for generating source code, following the conventions of this project.
    /// </summary>
    public static SymbolDisplayFormat SymbolDisplayFormat { get; } = SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
        SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions & ~SymbolDisplayMiscellaneousOptions.UseSpecialTypes
        | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
        | SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);
    
    /// <summary>
    ///     The <see cref="SymbolDisplayFormat"/>, adapted to not include generic type arguments.
    /// </summary>
    public static SymbolDisplayFormat SymbolDisplayFormatWithoutGenericTypeArguments { get; } = SymbolDisplayFormat.WithGenericsOptions(
        SymbolDisplayFormat.FullyQualifiedFormat.GenericsOptions & ~SymbolDisplayGenericsOptions.IncludeTypeParameters);

    /// <summary>
    ///     Generate a nested class structure based on the provided containing type information.
    ///     The content will be placed inside the innermost class.
    /// </summary>
    /// <param name="sb">The string builder to append to.</param>
    /// <param name="containingType">The containing type information defining the nesting structure.</param>
    /// <param name="builder">An action that appends the content to be placed inside the innermost class.</param>
    /// <returns>The modified string builder.</returns>
    public static StringBuilder AppendNestedClass(this StringBuilder sb, ContainingType? containingType, Action<StringBuilder, String> builder)
    {
        var nestedLevel = 0;
        var indent = "";

        while (containingType is not null)
        {
            sb.Append(containingType.Accessibility)
                .Append(' ')
                .Append("partial")
                .Append(' ')
                .Append(containingType.Keyword)
                .Append(' ')
                .Append(containingType.Name)
                .Append(containingType.TypeParameters);

            if (!String.IsNullOrWhiteSpace(containingType.Constraints))
                sb.Append(' ').Append(containingType.Constraints);

            sb.AppendLine().Append(indent).AppendLine("{");

            nestedLevel += 1;
            indent = new String(c: ' ', nestedLevel * 4);

            containingType = containingType.Child;
        }

        StringBuilder content = new();
        builder(content, indent);
        sb.AppendLine(content.ToString());

        while (nestedLevel > 0)
        {
            nestedLevel -= 1;

            indent = new String(c: ' ', nestedLevel * 4);
            sb.Append(indent).AppendLine("}");
        }

        return sb;
    }

    /// <summary>
    ///     Append a standard preamble for generated code files, including an auto-generated comment and the generator's name.
    /// </summary>
    /// <param name="sb">The string builder to append to.</param>
    /// <typeparam name="T">The type of the generator, used to include its name in the preamble.</typeparam>
    /// <returns>The string builder, for chaining.</returns>
    public static StringBuilder AppendPreamble<T>(this StringBuilder sb)
    {
        return sb.Append($"""
                          // <auto-generated />
                          // by {typeof(T).Name}

                          #nullable enable


                          """);
    }

    /// <summary>
    ///     Append a namespace declaration if the provided namespace is not null or whitespace.
    /// </summary>
    /// <param name="sb">The string builder to append to.</param>
    /// <param name="namespace">The namespace to append.</param>
    /// <returns>The modified string builder.</returns>
    public static StringBuilder AppendNamespace(this StringBuilder sb, String? @namespace)
    {
        if (!String.IsNullOrWhiteSpace(@namespace))
            sb.Append($"""
                       namespace {@namespace};


                       """);

        return sb;
    }
}
