// <copyright file="ComponentGeneratorTests.cs" company="VoxelGame">
//     VoxelGame - a voxel-based video game.
//     Copyright (C) 2026 Jean Patrick Mathes
//      
//     This program is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//     
//     This program is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
//     
//     You should have received a copy of the GNU General Public License
//     along with this program.  If not, see <https://www.gnu.org/licenses/>.
// </copyright>
// <author>jeanpmathes</author>

using System;
using VoxelGame.Annotations.Attributes;
using VoxelGame.SourceGenerators.Generators;
using VoxelGame.SourceGenerators.Tests.Utilities;
using Xunit;

namespace VoxelGame.SourceGenerators.Tests.Generators;

public class ComponentGeneratorTests
{
    [Fact]
    public void ComponentCompositionGenerator_ShouldGenerateSubjectAndComponentSources()
    {
        const String source = """
                              using System;
                              using VoxelGame.Annotations.Attributes;

                              namespace VoxelGame.Toolkit.Components
                              {
                                  public abstract class Component<TSubject>
                                  {
                                      protected Component(TSubject subject)
                                      {
                                          Subject = subject;
                                      }

                                      public TSubject Subject { get; }
                                  }

                                  public abstract class Composed<TSelf, TComponent>
                                      where TSelf : Composed<TSelf, TComponent>
                                      where TComponent : Component<TSelf>
                                  {
                                      protected abstract TSelf Self { get; }

                                      protected virtual void OnComponentAdded(TComponent component) {}

                                      protected virtual void OnComponentRemoved(TComponent component) {}
                                  }
                              }

                              namespace TestNamespace 
                              {
                                  [ComponentSubject(typeof(TestComponent))]
                                  public partial class TestSubject : VoxelGame.Toolkit.Components.Composed<TestSubject, TestComponent>
                                  {
                                      [ComponentEvent(nameof(TestComponent.OnEvent))]
                                      private partial void OnEvent();

                                      [ComponentEvent(nameof(TestComponent.OnParameterized))]
                                      public partial void OnParameterized(Int32 value);
                                  }

                                  public partial class TestComponent : VoxelGame.Toolkit.Components.Component<TestSubject>
                                  {
                                      public TestComponent(TestSubject subject) : base(subject) {}
                                  }
                              }
                              """;

        const String expectedSubject = """
                                       // <auto-generated />
                                       // by ComponentGenerator

                                       #nullable enable

                                       namespace TestNamespace;

                                       public partial class TestSubject
                                       {
                                           /// <inheritdoc />
                                           protected override TestSubject Self => this;

                                           private readonly global::System.Collections.Generic.HashSet<global::TestNamespace.TestComponent> @__onEventComponents = new();
                                           private readonly global::System.Collections.Generic.HashSet<global::TestNamespace.TestComponent> @__onEventPendingRemoval = new();

                                           private readonly global::System.Collections.Generic.HashSet<global::TestNamespace.TestComponent> @__onParameterizedComponents = new();
                                           private readonly global::System.Collections.Generic.HashSet<global::TestNamespace.TestComponent> @__onParameterizedPendingRemoval = new();

                                           private global::System.Int32 @__testSubjectComponentEventIterationDepth;

                                           /// <inheritdoc />
                                           protected override void OnComponentAdded(global::TestNamespace.TestComponent component)
                                           {
                                               RegisterComponentEvents(component);
                                           }

                                           /// <inheritdoc />
                                           protected override void OnComponentRemoved(global::TestNamespace.TestComponent component)
                                           {
                                               UnregisterComponentEvents(component);
                                           }

                                           private void RegisterComponentEvents(global::TestNamespace.TestComponent component)
                                           {
                                               @__onEventComponents.Add(component);
                                               @__onEventPendingRemoval.Remove(component);
                                               @__onParameterizedComponents.Add(component);
                                               @__onParameterizedPendingRemoval.Remove(component);
                                           }

                                           private void UnregisterComponentEvents(global::TestNamespace.TestComponent component)
                                           {
                                               Disable_OnEvent(component);
                                               Disable_OnParameterized(component);
                                           }

                                           internal void Disable_OnEvent(global::TestNamespace.TestComponent component)
                                           {
                                               if (@__testSubjectComponentEventIterationDepth > 0)
                                               {
                                                   @__onEventPendingRemoval.Add(component);
                                               }
                                               else
                                               {
                                                   @__onEventPendingRemoval.Remove(component);
                                                   @__onEventComponents.Remove(component);
                                               }
                                           }

                                           internal void Disable_OnParameterized(global::TestNamespace.TestComponent component)
                                           {
                                               if (@__testSubjectComponentEventIterationDepth > 0)
                                               {
                                                   @__onParameterizedPendingRemoval.Add(component);
                                               }
                                               else
                                               {
                                                   @__onParameterizedPendingRemoval.Remove(component);
                                                   @__onParameterizedComponents.Remove(component);
                                               }
                                           }

                                           private void FlushPendingTestSubjectEventRemovals()
                                           {
                                               foreach (var component in @__onEventPendingRemoval)
                                               {
                                                   @__onEventComponents.Remove(component);
                                               }
                                               @__onEventPendingRemoval.Clear();
                                               foreach (var component in @__onParameterizedPendingRemoval)
                                               {
                                                   @__onParameterizedComponents.Remove(component);
                                               }
                                               @__onParameterizedPendingRemoval.Clear();
                                           }

                                           private partial void OnEvent()
                                           {
                                               @__testSubjectComponentEventIterationDepth += 1;
                                               try
                                               {
                                                   foreach (var component in @__onEventComponents)
                                                   {
                                                       component.OnEvent();
                                                   }
                                               }
                                               finally
                                               {
                                                   @__testSubjectComponentEventIterationDepth -= 1;
                                                   if (@__testSubjectComponentEventIterationDepth == 0)
                                                       FlushPendingTestSubjectEventRemovals();
                                               }
                                           }

                                           public partial void OnParameterized(global::System.Int32 value)
                                           {
                                               @__testSubjectComponentEventIterationDepth += 1;
                                               try
                                               {
                                                   foreach (var component in @__onParameterizedComponents)
                                                   {
                                                       component.OnParameterized(value);
                                                   }
                                               }
                                               finally
                                               {
                                                   @__testSubjectComponentEventIterationDepth -= 1;
                                                   if (@__testSubjectComponentEventIterationDepth == 0)
                                                       FlushPendingTestSubjectEventRemovals();
                                               }
                                           }
                                       }

                                       """;

        const String expectedComponent = """
                                         // <auto-generated />
                                         // by ComponentGenerator

                                         #nullable enable

                                         namespace TestNamespace;

                                         public partial class TestComponent
                                         {
                                             /// <inheritdoc cref="global::TestNamespace.TestSubject.OnEvent" />
                                             public virtual void OnEvent()
                                             {
                                                 Subject.Disable_OnEvent(this);
                                             }
                                             /// <inheritdoc cref="global::TestNamespace.TestSubject.OnParameterized" />
                                             public virtual void OnParameterized(global::System.Int32 value)
                                             {
                                                 Subject.Disable_OnParameterized(this);
                                             }
                                         }

                                         """;

        String generatedSubject = TestTools.RunGenerator<ComponentGenerator>(source, "_ComponentSubject.g.cs", typeof(ComponentSubjectAttribute), typeof(ComponentEventAttribute));

        Assert.Equal(expectedSubject,
            generatedSubject,
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);

        String generatedComponent = TestTools.RunGenerator<ComponentGenerator>(source, "_Component.g.cs", typeof(ComponentSubjectAttribute), typeof(ComponentEventAttribute));

        Assert.Equal(expectedComponent,
            generatedComponent,
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }
}
