// <copyright file="ComponentGeneratorTests.cs" company="VoxelGame">
//     MIT License
//     For full license see the repository.
// </copyright>
// <author>jeanpmathes</author>

using System;
using VoxelGame.Annotations;
using VoxelGame.Annotations.Attributes;
using VoxelGame.SourceGenerators.Generators;
using VoxelGame.SourceGenerators.Tests.Utilities;
using Xunit;

namespace VoxelGame.SourceGenerators.Tests.Generators;

public class ComponentGeneratorTests
{
    [Fact]
    public void ComponentCompositionGenerator_GeneratesSubjectAndComponentSources()
    {
        const String source = """
                              using System;
                              using VoxelGame.Annotations;

                              namespace VoxelGame.Toolkit.Components
                              {
                                  public abstract class Component<TSubject>
                                  {
                                      protected Component(TSubject subject)
                                      {
                                          Subject = subject;
                                      }

                                      public TSubject Subject { get; }
                                  }

                                  public abstract class Composed<TSelf, TComponent>
                                      where TSelf : Composed<TSelf, TComponent>
                                      where TComponent : Component<TSelf>
                                  {
                                      protected abstract TSelf Self { get; }

                                      protected virtual void OnComponentAdded(TComponent component) {}

                                      protected virtual void OnComponentRemoved(TComponent component) {}
                                  }
                              }

                              namespace TestNamespace;

                              [ComponentSubject(typeof(TestComponent))]
                              public partial class TestSubject : VoxelGame.Toolkit.Components.Composed<TestSubject, TestComponent>
                              {
                                  [ComponentEvent(nameof(TestComponent.OnEvent))]
                                  private partial void OnEvent();

                                  [ComponentEvent(nameof(TestComponent.OnParameterized))]
                                  public partial void OnParameterized(Int32 value);
                              }

                              public partial class TestComponent : VoxelGame.Toolkit.Components.Component<TestSubject>
                              {
                                  public TestComponent(TestSubject subject) : base(subject) {}
                              }
                              """;

        const String expectedSubject = """
                                       // <auto-generated />
                                       // by ComponentGenerator

                                       #nullable enable

                                       namespace TestNamespace;

                                       public partial class TestSubject
                                       {
                                           protected override global::TestNamespace.TestSubject Self => this;

                                           private readonly global::System.Collections.Generic.HashSet<global::TestNamespace.TestComponent> @__onEventComponents = new();
                                           private readonly global::System.Collections.Generic.HashSet<global::TestNamespace.TestComponent> @__onEventComponentsPendingRemoval = new();

                                           private readonly global::System.Collections.Generic.HashSet<global::TestNamespace.TestComponent> @__onParameterizedComponents = new();
                                           private readonly global::System.Collections.Generic.HashSet<global::TestNamespace.TestComponent> @__onParameterizedComponentsPendingRemoval = new();

                                           private global::System.Int32 @__testSubjectComponentEventIterationDepth;

                                           protected override void OnComponentAdded(global::TestNamespace.TestComponent component)
                                           {
                                               base.OnComponentAdded(component);
                                               RegisterComponentEvents(component);
                                           }

                                           protected override void OnComponentRemoved(global::TestNamespace.TestComponent component)
                                           {
                                               base.OnComponentRemoved(component);
                                               UnregisterComponentEvents(component);
                                           }

                                           private void RegisterComponentEvents(global::TestNamespace.TestComponent component)
                                           {
                                               @__onEventComponents.Add(component);
                                               @__onEventComponentsPendingRemoval.Remove(component);
                                               @__onParameterizedComponents.Add(component);
                                               @__onParameterizedComponentsPendingRemoval.Remove(component);
                                           }

                                           private void UnregisterComponentEvents(global::TestNamespace.TestComponent component)
                                           {
                                               Disable_OnEvent(component);
                                               Disable_OnParameterized(component);
                                           }

                                           internal void Disable_OnEvent(global::TestNamespace.TestComponent component)
                                           {
                                               if (testSubjectComponentEventIterationDepth > 0)
                                               {
                                                   @__onEventComponentsPendingRemoval.Add(component);
                                               }
                                               else
                                               {
                                                   @__onEventComponentsPendingRemoval.Remove(component);
                                                   @__onEventComponents.Remove(component);
                                               }
                                           }

                                           internal void Disable_OnParameterized(global::TestNamespace.TestComponent component)
                                           {
                                               if (testSubjectComponentEventIterationDepth > 0)
                                               {
                                                   @__onParameterizedComponentsPendingRemoval.Add(component);
                                               }
                                               else
                                               {
                                                   @__onParameterizedComponentsPendingRemoval.Remove(component);
                                                   @__onParameterizedComponents.Remove(component);
                                               }
                                           }

                                           private void FlushPendingTestSubjectComponentEventRemovals()
                                           {
                                               foreach (global::TestNamespace.TestComponent component in onEventComponentsPendingRemoval)
                                               {
                                                   @__onEventComponents.Remove(component);
                                               }
                                               @__onEventComponentsPendingRemoval.Clear();

                                               foreach (global::TestNamespace.TestComponent component in onParameterizedComponentsPendingRemoval)
                                               {
                                                   @__onParameterizedComponents.Remove(component);
                                               }
                                               @__onParameterizedComponentsPendingRemoval.Clear();
                                           }

                                           private partial void OnEvent()
                                           {
                                               @__testSubjectComponentEventIterationDepth++;
                                               try
                                               {
                                                   foreach (global::TestNamespace.TestComponent component in onEventComponents)
                                                   {
                                                       component.OnEvent();
                                                   }
                                               }
                                               finally
                                               {
                                                   @__testSubjectComponentEventIterationDepth--;
                                                   if (@__testSubjectComponentEventIterationDepth == 0)
                                                       FlushPendingTestSubjectComponentEventRemovals();
                                               }
                                           }

                                           public partial void OnParameterized(global::System.Int32 value)
                                           {
                                               @__testSubjectComponentEventIterationDepth++;
                                               try
                                               {
                                                   foreach (global::TestNamespace.TestComponent component in onParameterizedComponents)
                                                   {
                                                       component.OnParameterized(value);
                                                   }
                                               }
                                               finally
                                               {
                                                   @__testSubjectComponentEventIterationDepth--;
                                                   if (testSubjectComponentEventIterationDepth == 0)
                                                       FlushPendingTestSubjectComponentEventRemovals();
                                               }
                                           }
                                       }

                                       """;

        const String expectedComponent = """
                                         // <auto-generated />
                                         // by ComponentGenerator

                                         #nullable enable

                                         namespace TestNamespace;

                                         public partial class TestComponent
                                         {
                                             public virtual void OnEvent()
                                             {
                                                 Subject.Disable_OnEvent(this);
                                             }

                                             public virtual void OnParameterized(global::System.Int32 value)
                                             {
                                                 Subject.Disable_OnParameterized(this);
                                             }
                                         }

                                         """;

        String generatedSubject = TestTools.RunGenerator<ComponentGenerator>(source, "TestNamespace.TestSubject_ComponentComposition.g.cs", typeof(ComponentSubjectAttribute), typeof(ComponentEventAttribute));

        Assert.Equal(expectedSubject,
            generatedSubject,
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);

        String generatedComponent = TestTools.RunGenerator<ComponentGenerator>(source, "TestNamespace.TestComponent_ComponentDefaults.g.cs", typeof(ComponentSubjectAttribute), typeof(ComponentEventAttribute));

        Assert.Equal(expectedComponent,
            generatedComponent,
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }
}
