// <copyright file="ConstructibleGeneratorTests.cs" company="VoxelGame">
//     MIT License
//     For full license see the repository.
// </copyright>
// <author>jeanpmathes</author>

using System;
using VoxelGame.Annotations.Attributes;
using VoxelGame.SourceGenerators.Generators;
using VoxelGame.SourceGenerators.Tests.Utilities;
using Xunit;

namespace VoxelGame.SourceGenerators.Tests.Generators;

public class ConstructibleGeneratorTests
{
    private static String RunGenerator(String source)
    {
        return TestTools.RunGenerator<ConstructibleGenerator>(source, "_Constructible.g.cs", typeof(ConstructibleAttribute));
    }

    [Fact]
    public void ConstructibleGenerator_ShouldGenerateForSingleParameter()
    {
        const String source = """
                             using System;
                             using VoxelGame.Annotations.Attributes;
                             namespace TestNamespace;

                             public partial class SingleParameterConstructible
                             {
                                 [Constructible]
                                 private SingleParameterConstructible(Int32 value)
                                 {
                                 }
                             }
                             """;

        const String expected = """
                                // <auto-generated />
                                // by ConstructibleGenerator

                                #nullable enable

                                namespace TestNamespace;

                                public partial class SingleParameterConstructible : global::VoxelGame.Toolkit.Utilities.IConstructible<global::System.Int32, global::TestNamespace.SingleParameterConstructible>
                                {
                                    /// <inheritdoc />
                                    public static global::TestNamespace.SingleParameterConstructible Construct(global::System.Int32 input)
                                    {
                                        return new global::TestNamespace.SingleParameterConstructible(input);
                                    }
                                }

                                """;

        Assert.Equal(expected, RunGenerator(source),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void ConstructibleGenerator_ShouldGenerateForTwoParameters()
    {
        const String source = """
                             using System;
                             using VoxelGame.Annotations.Attributes;
                             namespace TestNamespace;

                             public partial class TwoParameterConstructible
                             {
                                 [Constructible]
                                 private TwoParameterConstructible(Int32 first, String second)
                                 {
                                 }
                             }
                             """;

        const String expected = """
                                // <auto-generated />
                                // by ConstructibleGenerator

                                #nullable enable

                                namespace TestNamespace;

                                public partial class TwoParameterConstructible : global::VoxelGame.Toolkit.Utilities.IConstructible<global::System.Int32, global::System.String, global::TestNamespace.TwoParameterConstructible>
                                {
                                    /// <inheritdoc />
                                    public static global::TestNamespace.TwoParameterConstructible Construct(global::System.Int32 input1, global::System.String input2)
                                    {
                                        return new global::TestNamespace.TwoParameterConstructible(input1, input2);
                                    }
                                }

                                """;

        Assert.Equal(expected, RunGenerator(source),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void ConstructibleGenerator_ShouldGenerateForMultipleParameters()
    {
        const String source = """
                             using System;
                             using VoxelGame.Annotations.Attributes;
                             namespace TestNamespace;

                             public partial class MultiParameterConstructible
                             {
                                 [Constructible]
                                 private MultiParameterConstructible(Int32 first, String second, Double third)
                                 {
                                 }
                             }
                             """;

        const String expected = """
                                // <auto-generated />
                                // by ConstructibleGenerator

                                #nullable enable

                                namespace TestNamespace;

                                public partial class MultiParameterConstructible : global::VoxelGame.Toolkit.Utilities.IConstructible<global::System.Int32, (global::System.String, global::System.Double), global::TestNamespace.MultiParameterConstructible>
                                {
                                    /// <inheritdoc />
                                    public static global::TestNamespace.MultiParameterConstructible Construct(global::System.Int32 input1, (global::System.String, global::System.Double) input2)
                                    {
                                        return new global::TestNamespace.MultiParameterConstructible(input1, input2.Item1, input2.Item2);
                                    }
                                }

                                """;

        Assert.Equal(expected, RunGenerator(source),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }
}
