// <copyright file="ConstructibleGeneratorTests.cs" company="VoxelGame">
//     VoxelGame - a voxel-based video game.
//     Copyright (C) 2026 Jean Patrick Mathes
//      
//     This program is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//     
//     This program is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
//     
//     You should have received a copy of the GNU General Public License
//     along with this program.  If not, see <https://www.gnu.org/licenses/>.
// </copyright>
// <author>jeanpmathes</author>

using System;
using VoxelGame.Annotations.Attributes;
using VoxelGame.SourceGenerators.Generators;
using VoxelGame.SourceGenerators.Tests.Utilities;
using Xunit;

namespace VoxelGame.SourceGenerators.Tests.Generators;

public class ConstructibleGeneratorTests
{
    private static String RunGenerator(String source)
    {
        return TestTools.RunGenerator<ConstructibleGenerator>(source, "_Constructible.g.cs", typeof(ConstructibleAttribute));
    }

    [Fact]
    public void ConstructibleGenerator_ShouldGenerateForSingleParameter()
    {
        const String source = """
                              using System;
                              using VoxelGame.Annotations.Attributes;
                              namespace TestNamespace;

                              public partial class SingleParameterConstructible
                              {
                                  [Constructible]
                                  private SingleParameterConstructible(Int32 value)
                                  {
                                  }
                              }
                              """;

        const String expected = """
                                // <auto-generated />
                                // by ConstructibleGenerator

                                #nullable enable

                                namespace TestNamespace;

                                public partial class SingleParameterConstructible : global::VoxelGame.Toolkit.Utilities.IConstructible<global::System.Int32, global::TestNamespace.SingleParameterConstructible>
                                {
                                    /// <inheritdoc />
                                    public static global::TestNamespace.SingleParameterConstructible Construct(global::System.Int32 input)
                                    {
                                        return new global::TestNamespace.SingleParameterConstructible(input);
                                    }
                                }

                                """;

        Assert.Equal(expected,
            RunGenerator(source),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void ConstructibleGenerator_ShouldGenerateForTwoParameters()
    {
        const String source = """
                              using System;
                              using VoxelGame.Annotations.Attributes;
                              namespace TestNamespace;

                              public partial class TwoParameterConstructible
                              {
                                  [Constructible]
                                  private TwoParameterConstructible(Int32 first, String second)
                                  {
                                  }
                              }
                              """;

        const String expected = """
                                // <auto-generated />
                                // by ConstructibleGenerator

                                #nullable enable

                                namespace TestNamespace;

                                public partial class TwoParameterConstructible : global::VoxelGame.Toolkit.Utilities.IConstructible<global::System.Int32, global::System.String, global::TestNamespace.TwoParameterConstructible>
                                {
                                    /// <inheritdoc />
                                    public static global::TestNamespace.TwoParameterConstructible Construct(global::System.Int32 input1, global::System.String input2)
                                    {
                                        return new global::TestNamespace.TwoParameterConstructible(input1, input2);
                                    }
                                }

                                """;

        Assert.Equal(expected,
            RunGenerator(source),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void ConstructibleGenerator_ShouldGenerateForMultipleParameters()
    {
        const String source = """
                              using System;
                              using VoxelGame.Annotations.Attributes;
                              namespace TestNamespace;

                              public partial class MultiParameterConstructible
                              {
                                  [Constructible]
                                  private MultiParameterConstructible(Int32 first, String second, Double third)
                                  {
                                  }
                              }
                              """;

        const String expected = """
                                // <auto-generated />
                                // by ConstructibleGenerator

                                #nullable enable

                                namespace TestNamespace;

                                public partial class MultiParameterConstructible : global::VoxelGame.Toolkit.Utilities.IConstructible<global::System.Int32, (global::System.String, global::System.Double), global::TestNamespace.MultiParameterConstructible>
                                {
                                    /// <inheritdoc />
                                    public static global::TestNamespace.MultiParameterConstructible Construct(global::System.Int32 input1, (global::System.String, global::System.Double) input2)
                                    {
                                        return new global::TestNamespace.MultiParameterConstructible(input1, input2.Item1, input2.Item2);
                                    }
                                }

                                """;

        Assert.Equal(expected,
            RunGenerator(source),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }
}
