// <copyright file="EnumUtilityGeneratorTests.cs" company="VoxelGame">
//     MIT License
//     For full license see the repository.
// </copyright>
// <author>jeanpmathes</author>

using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using VoxelGame.SourceGenerators.Generators;
using Xunit;

namespace VoxelGame.SourceGenerators.Tests.Generators;

public class EnumUtilityGeneratorTests
{
    [Fact]
    public void EnumUtilityGenerator_ShouldGenerateExtensionMethodForEnum()
    {
        const String oldText = """

                               namespace TestNamespace;

                               public enum TestEnum
                               {
                                   A = 1,
                                   B = 2,
                                   C = 4
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by EnumUtilityGenerator

                               #nullable enable

                               namespace TestNamespace;

                               /// <ignore />
                               public static partial class EnumExtensions
                               {
                                   /// <summary>
                                   /// A faster alternative to <see cref="global::System.Object.ToString"/> for the enum <see cref="global::TestNamespace.TestEnum"/>.
                                   /// </summary>
                                   public static global::System.String ToStringFast(this global::TestNamespace.TestEnum value) 
                                       => value switch
                                       {
                                           global::TestNamespace.TestEnum.A => nameof(global::TestNamespace.TestEnum.A),
                                           global::TestNamespace.TestEnum.B => nameof(global::TestNamespace.TestEnum.B),
                                           global::TestNamespace.TestEnum.C => nameof(global::TestNamespace.TestEnum.C),

                                           _ => value.ToString()
                                       };
                               }

                               """;

        EnumUtilityGenerator generator = new();
        var driver = CSharpGeneratorDriver.Create(generator);

        var compilation = CSharpCompilation.Create(nameof(EnumUtilityGeneratorTests),
            [CSharpSyntaxTree.ParseText(oldText)],
            [MetadataReference.CreateFromFile(typeof(Object).Assembly.Location)]);

        GeneratorDriverRunResult runResult = driver.RunGenerators(compilation).GetRunResult();
        SyntaxTree generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("TestEnum.g.cs"));

        Assert.Equal(newText,
            generatedFileSyntax.GetText().ToString(),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }
}
