// <copyright file="EnumUtilityGeneratorTests.cs" company="VoxelGame">
//     MIT License
//     For full license see the repository.
// </copyright>
// <author>jeanpmathes</author>

using System;
using VoxelGame.SourceGenerators.Generators;
using VoxelGame.SourceGenerators.Tests.Utilities;
using Xunit;

namespace VoxelGame.SourceGenerators.Tests.Generators;

public class EnumUtilityGeneratorTests
{
    private static String RunGenerator(String source)
    {
        return TestTools.RunGenerator<EnumUtilityGenerator>(source, "_EnumUtility.g.cs");
    }
    
    [Fact]
    public void EnumUtilityGenerator_ShouldGenerateExtensionMethodForEnum()
    {
        const String oldText = """

                               namespace TestNamespace;

                               public enum TestEnum
                               {
                                   A = 1,
                                   B = 2,
                                   C = 4
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by EnumUtilityGenerator

                               #nullable enable

                               namespace TestNamespace;

                               /// <summary />
                               public static partial class EnumExtensions
                               {
                                   /// <summary>
                                   /// A faster alternative to <see cref="global::System.Object.ToString"/> for the enum <see cref="global::TestNamespace.TestEnum"/>.
                                   /// </summary>
                                   public static global::System.String ToStringFast(this global::TestNamespace.TestEnum value) 
                                       => value switch
                                       {
                                           global::TestNamespace.TestEnum.A => nameof(global::TestNamespace.TestEnum.A),
                                           global::TestNamespace.TestEnum.B => nameof(global::TestNamespace.TestEnum.B),
                                           global::TestNamespace.TestEnum.C => nameof(global::TestNamespace.TestEnum.C),

                                           _ => value.ToString()
                                       };
                               }

                               """;

        Assert.Equal(newText, RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }
}
