// <copyright file="EnumUtilityGeneratorTests.cs" company="VoxelGame">
//     VoxelGame - a voxel-based video game.
//     Copyright (C) 2026 Jean Patrick Mathes
//      
//     This program is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//     
//     This program is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
//     
//     You should have received a copy of the GNU General Public License
//     along with this program.  If not, see <https://www.gnu.org/licenses/>.
// </copyright>
// <author>jeanpmathes</author>

using System;
using VoxelGame.SourceGenerators.Generators;
using VoxelGame.SourceGenerators.Tests.Utilities;
using Xunit;

namespace VoxelGame.SourceGenerators.Tests.Generators;

public class EnumUtilityGeneratorTests
{
    private static String RunGenerator(String source)
    {
        return TestTools.RunGenerator<EnumUtilityGenerator>(source, "_EnumUtility.g.cs");
    }

    [Fact]
    public void EnumUtilityGenerator_ShouldGenerateExtensionMethodForEnum()
    {
        const String oldText = """

                               namespace TestNamespace;

                               public enum TestEnum
                               {
                                   A = 1,
                                   B = 2,
                                   C = 4
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by EnumUtilityGenerator

                               #nullable enable

                               namespace TestNamespace;

                               /// <summary />
                               public static partial class EnumExtensions
                               {
                                   /// <summary>
                                   /// A faster alternative to <see cref="global::System.Object.ToString"/> for the enum <see cref="global::TestNamespace.TestEnum"/>.
                                   /// </summary>
                                   public static global::System.String ToStringFast(this global::TestNamespace.TestEnum value) 
                                       => value switch
                                       {
                                           global::TestNamespace.TestEnum.A => nameof(global::TestNamespace.TestEnum.A),
                                           global::TestNamespace.TestEnum.B => nameof(global::TestNamespace.TestEnum.B),
                                           global::TestNamespace.TestEnum.C => nameof(global::TestNamespace.TestEnum.C),

                                           _ => value.ToString()
                                       };
                               }

                               """;

        Assert.Equal(newText,
            RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }
}
