// <copyright file="GenerateRecordGeneratorTests.cs" company="VoxelGame">
//     MIT License
//     For full license see the repository.
// </copyright>
// <author>jeanpmathes</author>

using System;
using VoxelGame.Annotations.Attributes;
using VoxelGame.SourceGenerators.Generators;
using VoxelGame.SourceGenerators.Tests.Utilities;
using Xunit;

namespace VoxelGame.SourceGenerators.Tests.Generators;

public class GenerateRecordGeneratorTests
{
    private static String RunGenerator(String source)
    {
        return TestTools.RunGenerator<GenerateRecordGenerator>(source, "_Record.g.cs", typeof(GenerateRecordAttribute));
    }
    
    [Fact]
    public void GenerateRecordGenerator_ShouldGenerateForNestedInterface()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations;

                               namespace TestNamespace;

                               public partial class Container
                               {
                                   [GenerateRecord]
                                   public interface INested
                                   {
                                       public Int32 X { get; set; }
                                   }
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by GenerateRecordGenerator

                               #nullable enable

                               namespace TestNamespace;

                               public partial class Container
                               {
                                   /// <summary>
                                   ///     Implementation of <see cref="global::TestNamespace.Container.INested" />.
                                   /// </summary>
                                   private partial record Nested : global::TestNamespace.Container.INested
                                   {
                                       public global::System.Int32 X { get; set; }
                                   }
                               }

                               """;

        Assert.Equal(newText, RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void GenerateRecordGenerator_ShouldGenerateForNonNestedInterface()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations;

                               namespace TestNamespace;

                               public struct Vector3i {}

                               [GenerateRecord]
                               public interface ITest
                               {
                                   public Int32 X { get; set; }
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by GenerateRecordGenerator

                               #nullable enable

                               namespace TestNamespace;

                               /// <summary>
                               ///     Implementation of <see cref="global::TestNamespace.ITest" />.
                               /// </summary>
                               public partial record Test : global::TestNamespace.ITest
                               {
                                   public global::System.Int32 X { get; set; }
                               }

                               """;

        Assert.Equal(newText, RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void GenerateRecordGenerator_ShouldGenerateForInterfaceWithZeroProperties()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations;

                               namespace TestNamespace;

                               [GenerateRecord]
                               public interface IEmpty
                               {
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by GenerateRecordGenerator

                               #nullable enable

                               namespace TestNamespace;

                               /// <summary>
                               ///     Implementation of <see cref="global::TestNamespace.IEmpty" />.
                               /// </summary>
                               public partial record Empty : global::TestNamespace.IEmpty
                               {
                               }

                               """;

        Assert.Equal(newText, RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void GenerateRecordGenerator_ShouldGenerateAndIgnoreMethods()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations;

                               namespace TestNamespace;

                               [GenerateRecord]
                               public interface IWithMethods
                               {
                                   public Int32 X { get; set; }

                                   public void AMethod() { }
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by GenerateRecordGenerator

                               #nullable enable

                               namespace TestNamespace;

                               /// <summary>
                               ///     Implementation of <see cref="global::TestNamespace.IWithMethods" />.
                               /// </summary>
                               public partial record WithMethods : global::TestNamespace.IWithMethods
                               {
                                   public global::System.Int32 X { get; set; }
                               }

                               """;

        Assert.Equal(newText, RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void GenerateRecordGenerator_ShouldInitializeNonNullableReferenceProperties()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations;

                               namespace TestNamespace;

                               [GenerateRecord]
                               public interface IWithReference
                               {
                                   public String Text { get; set; }
                                   public String? NullableText { get; set; }
                                   public Int32 Number { get; set; }
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by GenerateRecordGenerator

                               #nullable enable

                               namespace TestNamespace;

                               /// <summary>
                               ///     Implementation of <see cref="global::TestNamespace.IWithReference" />.
                               /// </summary>
                               public partial record WithReference : global::TestNamespace.IWithReference
                               {
                                   public global::System.String Text { get; set; } = null!;
                                   public global::System.String? NullableText { get; set; }
                                   public global::System.Int32 Number { get; set; }
                               }

                               """;

        Assert.Equal(newText, RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }
    
    [Fact]
    public void GenerateRecordGenerator_ShouldGenerateWithBaseType()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations;

                               namespace TestNamespace;

                               public class BaseClass;

                               [GenerateRecord(typeof(BaseClass))]
                               public interface IWithBase;
                               """;

        const String newText = """
                               // <auto-generated />
                               // by GenerateRecordGenerator

                               #nullable enable

                               namespace TestNamespace;

                               /// <summary>
                               ///     Implementation of <see cref="global::TestNamespace.IWithBase" />.
                               /// </summary>
                               public partial record WithBase : global::TestNamespace.BaseClass, global::TestNamespace.IWithBase
                               {
                               }

                               """;

        Assert.Equal(newText, RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }
    
    [Fact]
    public void GenerateRecordGenerator_ShouldGenerateWithUnboundedGenericBaseType()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations;

                               namespace TestNamespace;

                               public class BaseClass<T>;

                               [GenerateRecord(typeof(BaseClass<>))]
                               public interface IWithBase;
                               """;

        const String newText = """
                               // <auto-generated />
                               // by GenerateRecordGenerator

                               #nullable enable

                               namespace TestNamespace;

                               /// <summary>
                               ///     Implementation of <see cref="global::TestNamespace.IWithBase" />.
                               /// </summary>
                               public partial record WithBase : global::TestNamespace.BaseClass<WithBase>, global::TestNamespace.IWithBase
                               {
                               }

                               """;
        
        Assert.Equal(newText, RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }
    
    [Fact]
    public void GenerateRecordGenerator_ShouldGenerateWithGenericBaseType()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations;

                               namespace TestNamespace;

                               public class BaseClass<T> { }

                               [GenerateRecord(typeof(BaseClass<Int32>))]
                               public interface IWithBase;
                               """;

        const String newText = """
                               // <auto-generated />
                               // by GenerateRecordGenerator

                               #nullable enable

                               namespace TestNamespace;

                               /// <summary>
                               ///     Implementation of <see cref="global::TestNamespace.IWithBase" />.
                               /// </summary>
                               public partial record WithBase : global::TestNamespace.BaseClass<global::System.Int32>, global::TestNamespace.IWithBase
                               {
                               }

                               """;

        Assert.Equal(newText, RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }
}
