// <copyright file="GenerateRecordGeneratorTests.cs" company="VoxelGame">
//     VoxelGame - a voxel-based video game.
//     Copyright (C) 2026 Jean Patrick Mathes
//      
//     This program is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//     
//     This program is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
//     
//     You should have received a copy of the GNU General Public License
//     along with this program.  If not, see <https://www.gnu.org/licenses/>.
// </copyright>
// <author>jeanpmathes</author>

using System;
using VoxelGame.Annotations.Attributes;
using VoxelGame.SourceGenerators.Generators;
using VoxelGame.SourceGenerators.Tests.Utilities;
using Xunit;

namespace VoxelGame.SourceGenerators.Tests.Generators;

public class GenerateRecordGeneratorTests
{
    private static String RunGenerator(String source)
    {
        return TestTools.RunGenerator<GenerateRecordGenerator>(source, "_Record.g.cs", typeof(GenerateRecordAttribute));
    }

    [Fact]
    public void GenerateRecordGenerator_ShouldGenerateForNestedInterface()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations.Attributes;

                               namespace TestNamespace;

                               public partial class Container
                               {
                                   [GenerateRecord]
                                   public interface INested
                                   {
                                       public Int32 X { get; set; }
                                   }
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by GenerateRecordGenerator

                               #nullable enable

                               namespace TestNamespace;

                               public partial class Container
                               {
                                   /// <summary>
                                   ///     Implementation of <see cref="global::TestNamespace.Container.INested" />.
                                   /// </summary>
                                   private sealed partial record Nested : global::TestNamespace.Container.INested
                                   {
                                       public global::System.Int32 X { get; set; }
                                   }
                               }

                               """;

        Assert.Equal(newText,
            RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void GenerateRecordGenerator_ShouldGenerateForNonNestedInterface()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations.Attributes;

                               namespace TestNamespace;

                               public struct Vector3i {}

                               [GenerateRecord]
                               public interface ITest
                               {
                                   public Int32 X { get; set; }
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by GenerateRecordGenerator

                               #nullable enable

                               namespace TestNamespace;

                               /// <summary>
                               ///     Implementation of <see cref="global::TestNamespace.ITest" />.
                               /// </summary>
                               public sealed partial record Test : global::TestNamespace.ITest
                               {
                                   public global::System.Int32 X { get; set; }
                               }

                               """;

        Assert.Equal(newText,
            RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void GenerateRecordGenerator_ShouldGenerateForInterfaceWithZeroProperties()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations.Attributes;

                               namespace TestNamespace;

                               [GenerateRecord]
                               public interface IEmpty
                               {
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by GenerateRecordGenerator

                               #nullable enable

                               namespace TestNamespace;

                               /// <summary>
                               ///     Implementation of <see cref="global::TestNamespace.IEmpty" />.
                               /// </summary>
                               public sealed partial record Empty : global::TestNamespace.IEmpty
                               {
                               }

                               """;

        Assert.Equal(newText,
            RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void GenerateRecordGenerator_ShouldGenerateAndIgnoreMethods()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations.Attributes;

                               namespace TestNamespace;

                               [GenerateRecord]
                               public interface IWithMethods
                               {
                                   public Int32 X { get; set; }

                                   public void AMethod() { }
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by GenerateRecordGenerator

                               #nullable enable

                               namespace TestNamespace;

                               /// <summary>
                               ///     Implementation of <see cref="global::TestNamespace.IWithMethods" />.
                               /// </summary>
                               public sealed partial record WithMethods : global::TestNamespace.IWithMethods
                               {
                                   public global::System.Int32 X { get; set; }
                               }

                               """;

        Assert.Equal(newText,
            RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void GenerateRecordGenerator_ShouldInitializeNonNullableReferenceProperties()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations.Attributes;

                               namespace TestNamespace;

                               [GenerateRecord]
                               public interface IWithReference
                               {
                                   public String Text { get; set; }
                                   public String? NullableText { get; set; }
                                   public Int32 Number { get; set; }
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by GenerateRecordGenerator

                               #nullable enable

                               namespace TestNamespace;

                               /// <summary>
                               ///     Implementation of <see cref="global::TestNamespace.IWithReference" />.
                               /// </summary>
                               public sealed partial record WithReference : global::TestNamespace.IWithReference
                               {
                                   public global::System.String Text { get; set; } = null!;
                                   public global::System.String? NullableText { get; set; }
                                   public global::System.Int32 Number { get; set; }
                               }

                               """;

        Assert.Equal(newText,
            RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void GenerateRecordGenerator_ShouldGenerateWithBaseType()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations.Attributes;

                               namespace TestNamespace;

                               public class BaseClass;

                               [GenerateRecord(typeof(BaseClass))]
                               public interface IWithBase;
                               """;

        const String newText = """
                               // <auto-generated />
                               // by GenerateRecordGenerator

                               #nullable enable

                               namespace TestNamespace;

                               /// <summary>
                               ///     Implementation of <see cref="global::TestNamespace.IWithBase" />.
                               /// </summary>
                               public sealed partial record WithBase : global::TestNamespace.BaseClass, global::TestNamespace.IWithBase
                               {
                               }

                               """;

        Assert.Equal(newText,
            RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void GenerateRecordGenerator_ShouldGenerateWithUnboundedGenericBaseType()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations.Attributes;

                               namespace TestNamespace;

                               public class BaseClass<T>;

                               [GenerateRecord(typeof(BaseClass<>))]
                               public interface IWithBase;
                               """;

        const String newText = """
                               // <auto-generated />
                               // by GenerateRecordGenerator

                               #nullable enable

                               namespace TestNamespace;

                               /// <summary>
                               ///     Implementation of <see cref="global::TestNamespace.IWithBase" />.
                               /// </summary>
                               public sealed partial record WithBase : global::TestNamespace.BaseClass<WithBase>, global::TestNamespace.IWithBase
                               {
                               }

                               """;

        Assert.Equal(newText,
            RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void GenerateRecordGenerator_ShouldGenerateWithGenericBaseType()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations.Attributes;

                               namespace TestNamespace;

                               public class BaseClass<T> { }

                               [GenerateRecord(typeof(BaseClass<Int32>))]
                               public interface IWithBase;
                               """;

        const String newText = """
                               // <auto-generated />
                               // by GenerateRecordGenerator

                               #nullable enable

                               namespace TestNamespace;

                               /// <summary>
                               ///     Implementation of <see cref="global::TestNamespace.IWithBase" />.
                               /// </summary>
                               public sealed partial record WithBase : global::TestNamespace.BaseClass<global::System.Int32>, global::TestNamespace.IWithBase
                               {
                               }

                               """;

        Assert.Equal(newText,
            RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }
}
