// <copyright file="LateInitializationGeneratorTests.cs" company="VoxelGame">
//     MIT License
//     For full license see the repository.
// </copyright>
// <author>jeanpmathes</author>

using System;
using VoxelGame.SourceGenerators.Generators;
using VoxelGame.SourceGenerators.Tests.Utilities;
using Xunit;

namespace VoxelGame.SourceGenerators.Tests.Generators;

public class LateInitializationGeneratorTests
{
    private static String RunGenerator(String source)
    {
        return TestTools.RunGenerator<LateInitializationGenerator>(source, "_LateInitialization.g.cs");
    }
    
    [Fact]
    public void LateInitializationGenerator_ShouldGeneratePropertyForReferenceTypeProperty()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations.Attributes;

                               namespace TestNamespace;

                               public partial class TestClass
                               {
                                   [LateInitialization]
                                   private partial String Data { get; set; }
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by LateInitializationGenerator

                               #nullable enable

                               namespace TestNamespace;

                               public partial class TestClass
                               {
                                   private global::System.String? @__data;

                                   private partial global::System.String Data
                                   {
                                       get => @__data 
                                           ?? throw new global::System.InvalidOperationException($"Property '{nameof(Data)}' is used before being initialized.");

                                       set
                                       {
                                           if (@__data is not null)
                                               throw new global::System.InvalidOperationException($"Property '{nameof(Data)}' is already initialized.");

                                           @__data = value;
                                       }
                                   } 
                               }

                               """;

        Assert.Equal(newText, RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void LateInitializationGenerator_ShouldGeneratePropertyForValueTypeProperty()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations.Attributes;

                               namespace TestNamespace;

                               public partial class TestClass
                               {
                                   [LateInitialization]
                                   public partial Int32 Value { get; set; }
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by LateInitializationGenerator

                               #nullable enable

                               namespace TestNamespace;

                               public partial class TestClass
                               {
                                   private global::System.Int32? @__value;

                                   public partial global::System.Int32 Value
                                   {
                                       get => @__value 
                                           ?? throw new global::System.InvalidOperationException($"Property '{nameof(Value)}' is used before being initialized.");

                                       set
                                       {
                                                                                      if (@__value is not null)
                                               throw new global::System.InvalidOperationException($"Property '{nameof(Value)}' is already initialized.");

                                           @__value = value;
                                       }
                                   } 
                               }

                               """;
        
        Assert.Equal(newText, RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }
    
    [Fact]
    public void LateInitializationGenerator_ShouldPreserveAccessibilityModifiers()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations.Attributes;

                               namespace TestNamespace;

                               public partial class TestClass
                               {
                                   [LateInitialization]
                                   public partial Double Data { private get; set; }
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by LateInitializationGenerator

                               #nullable enable

                               namespace TestNamespace;

                               public partial class TestClass
                               {
                                   private global::System.Double? @__data;

                                   public partial global::System.Double Data
                                   {
                                       private get => @__data 
                                           ?? throw new global::System.InvalidOperationException($"Property '{nameof(Data)}' is used before being initialized.");

                                       set
                                       {
                                           if (@__data is not null)
                                               throw new global::System.InvalidOperationException($"Property '{nameof(Data)}' is already initialized.");

                                           @__data = value;
                                       }
                                   } 
                               }

                               """;

        Assert.Equal(newText, RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }
}
