// <copyright file="LateInitializationGeneratorTests.cs" company="VoxelGame">
//     VoxelGame - a voxel-based video game.
//     Copyright (C) 2025 Jean Patrick Mathes
//      
//     This program is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//     
//     This program is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
//     
//     You should have received a copy of the GNU General Public License
//     along with this program.  If not, see <https://www.gnu.org/licenses/>.
// </copyright>
// <author>jeanpmathes</author>

using System;
using VoxelGame.SourceGenerators.Generators;
using VoxelGame.SourceGenerators.Tests.Utilities;
using Xunit;

namespace VoxelGame.SourceGenerators.Tests.Generators;

public class LateInitializationGeneratorTests
{
    private static String RunGenerator(String source)
    {
        return TestTools.RunGenerator<LateInitializationGenerator>(source, "_LateInitialization.g.cs");
    }

    [Fact]
    public void LateInitializationGenerator_ShouldGeneratePropertyForReferenceTypeProperty()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations.Attributes;

                               namespace TestNamespace;

                               public partial class TestClass
                               {
                                   [LateInitialization]
                                   private partial String Data { get; set; }
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by LateInitializationGenerator

                               #nullable enable

                               namespace TestNamespace;

                               public partial class TestClass
                               {
                                   private global::System.String? @__data;

                                   private partial global::System.String Data
                                   {
                                       get => @__data 
                                           ?? throw new global::System.InvalidOperationException($"Property '{nameof(Data)}' is used before being initialized.");

                                       set
                                       {
                                           if (@__data is not null)
                                               throw new global::System.InvalidOperationException($"Property '{nameof(Data)}' is already initialized.");

                                           @__data = value;
                                       }
                                   } 
                               }

                               """;

        Assert.Equal(newText,
            RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void LateInitializationGenerator_ShouldGeneratePropertyForValueTypeProperty()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations.Attributes;

                               namespace TestNamespace;

                               public partial class TestClass
                               {
                                   [LateInitialization]
                                   public partial Int32 Value { get; set; }
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by LateInitializationGenerator

                               #nullable enable

                               namespace TestNamespace;

                               public partial class TestClass
                               {
                                   private global::System.Int32? @__value;

                                   public partial global::System.Int32 Value
                                   {
                                       get => @__value 
                                           ?? throw new global::System.InvalidOperationException($"Property '{nameof(Value)}' is used before being initialized.");

                                       set
                                       {
                                                                                      if (@__value is not null)
                                               throw new global::System.InvalidOperationException($"Property '{nameof(Value)}' is already initialized.");

                                           @__value = value;
                                       }
                                   } 
                               }

                               """;

        Assert.Equal(newText,
            RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void LateInitializationGenerator_ShouldPreserveAccessibilityModifiers()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations.Attributes;

                               namespace TestNamespace;

                               public partial class TestClass
                               {
                                   [LateInitialization]
                                   public partial Double Data { private get; set; }
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by LateInitializationGenerator

                               #nullable enable

                               namespace TestNamespace;

                               public partial class TestClass
                               {
                                   private global::System.Double? @__data;

                                   public partial global::System.Double Data
                                   {
                                       private get => @__data 
                                           ?? throw new global::System.InvalidOperationException($"Property '{nameof(Data)}' is used before being initialized.");

                                       set
                                       {
                                           if (@__data is not null)
                                               throw new global::System.InvalidOperationException($"Property '{nameof(Data)}' is already initialized.");

                                           @__data = value;
                                       }
                                   } 
                               }

                               """;

        Assert.Equal(newText,
            RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }
}
