// <copyright file="LateInitializationGeneratorTests.cs" company="VoxelGame">
//     MIT License
//     For full license see the repository.
// </copyright>
// <author>jeanpmathes</author>

using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using VoxelGame.Annotations;
using VoxelGame.SourceGenerators.Generators;
using Xunit;

namespace VoxelGame.SourceGenerators.Tests.Generators;

public class LateInitializationGeneratorTests
{
    [Fact]
    public void LateInitializationGenerator_ShouldGeneratePropertyForReferenceTypeProperty()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations;

                               namespace TestNamespace;

                               public partial class TestClass
                               {
                                   [LateInitialization]
                                   private partial String Data { get; set; }
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by LateInitializationGenerator

                               #nullable enable

                               namespace TestNamespace;

                               public partial class TestClass
                               {
                                   private global::System.String? @__data;

                                   private partial global::System.String Data
                                   {
                                       get => @__data ?? throw new global::System.InvalidOperationException($"Property '{nameof(Data)}' is used before being initialized.");
                                       set
                                       {
                                           if (@__data is not null)
                                               throw new global::System.InvalidOperationException($"Property '{nameof(Data)}' is already initialized.");

                                           @__data = value;
                                       }
                                   } 
                               }

                               """;

        var generator = new LateInitializationGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);

        var compilation = CSharpCompilation.Create(nameof(LateInitializationGenerator_ShouldGeneratePropertyForReferenceTypeProperty),
            [CSharpSyntaxTree.ParseText(oldText)],
            [
                MetadataReference.CreateFromFile(typeof(Object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(LateInitializationAttribute).Assembly.Location)
            ]);

        GeneratorDriverRunResult runResult = driver.RunGenerators(compilation).GetRunResult();
        SyntaxTree generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("LateInitialization.g.cs"));

        Assert.Equal(newText,
            generatedFileSyntax.GetText().ToString(),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void LateInitializationGenerator_ShouldGeneratePropertyForValueTypeProperty()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations;

                               namespace TestNamespace;

                               public partial class TestClass
                               {
                                   [LateInitialization]
                                   public partial Int32 Value { get; set; }
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by LateInitializationGenerator

                               #nullable enable

                               namespace TestNamespace;

                               public partial class TestClass
                               {
                                   private global::System.Int32? @__value;

                                   public partial global::System.Int32 Value
                                   {
                                       get => @__value ?? throw new global::System.InvalidOperationException($"Property '{nameof(Value)}' is used before being initialized.");
                                       set
                                       {
                                                                                      if (@__value is not null)
                                               throw new global::System.InvalidOperationException($"Property '{nameof(Value)}' is already initialized.");

                                           @__value = value;
                                       }
                                   } 
                               }

                               """;

        var generator = new LateInitializationGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);

        var compilation = CSharpCompilation.Create(nameof(LateInitializationGenerator_ShouldGeneratePropertyForValueTypeProperty),
            [CSharpSyntaxTree.ParseText(oldText)],
            [
                MetadataReference.CreateFromFile(typeof(Object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(LateInitializationAttribute).Assembly.Location)
            ]);

        GeneratorDriverRunResult runResult = driver.RunGenerators(compilation).GetRunResult();
        SyntaxTree generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("LateInitialization.g.cs"));

        Assert.Equal(newText,
            generatedFileSyntax.GetText().ToString(),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }
}
