// <copyright file="MeasureGeneratorTests.cs" company="VoxelGame">
//     MIT License
//     For full license see the repository.
// </copyright>
// <author>jeanpmathes</author>

using System;
using VoxelGame.Annotations.Attributes;
using VoxelGame.SourceGenerators.Generators;
using VoxelGame.SourceGenerators.Tests.Utilities;
using Xunit;

namespace VoxelGame.SourceGenerators.Tests.Generators;

public class MeasureGeneratorTests
{
    private static String RunGenerator(String source)
    {
        return TestTools.RunGenerator<MeasureGenerator>(source, "_Measure.g.cs", typeof(GenerateMeasureAttribute));
    }

    [Fact]
    public void MeasureGenerator_ShouldGenerateMeasureStruct()
    {
        const String source = """
                             using System;
                             using VoxelGame.Annotations.Attributes;
                             using VoxelGame.Annotations.Definitions;

                             namespace VoxelGame.Core.Utilities.Units;

                             public record Unit(String Symbol)
                             {
                                 [GenerateMeasure(
                                     "Length",
                                     "Meters",
                                     AllowedPrefixes.None,
                                     MeasureSummary = "A measure for length.",
                                     ValueSummary = "Get the length, in meters.")]
                                 public static Unit Meter { get; } = new("m");
                             }
                             """;

        const String expected = """
                                // <auto-generated />
                                // by MeasureGenerator

                                #nullable enable

                                namespace VoxelGame.Core.Utilities.Units;

                                /// <summary>
                                ///     A measure for length.
                                /// </summary>
                                public readonly partial struct Length 
                                    : global::VoxelGame.Core.Utilities.Units.IMeasure
                                    , global::System.IEquatable<Length>
                                    , global::System.IComparable<Length>
                                    , global::System.Numerics.IComparisonOperators<Length, Length, global::System.Boolean>
                                {
                                    /// <summary>
                                    ///     Get the length, in meters.
                                    /// </summary>
                                    public global::System.Double Meters { get; init; }

                                    /// <inheritdoc />
                                    public static global::VoxelGame.Core.Utilities.Units.Unit Unit => global::VoxelGame.Core.Utilities.Units.Unit.Meter;

                                    /// <inheritdoc />
                                    public static global::VoxelGame.Annotations.Definitions.AllowedPrefixes Prefixes => (global::VoxelGame.Annotations.Definitions.AllowedPrefixes) 0;

                                    /// <inheritdoc />
                                    global::System.Double global::VoxelGame.Core.Utilities.Units.IMeasure.Value => Meters;

                                    /// <inheritdoc />
                                    public global::System.Boolean Equals(Length other)
                                    {
                                        return Meters.Equals(other.Meters);
                                    }

                                    /// <inheritdoc />
                                    public override global::System.Boolean Equals(global::System.Object? obj)
                                    {
                                        return obj is Length other && Equals(other);
                                    }
                                
                                    /// <inheritdoc />
                                    public global::System.Int32 CompareTo(Length other)
                                    {
                                        return Meters.CompareTo(other.Meters);
                                    }

                                    /// <inheritdoc />
                                    public override global::System.Int32 GetHashCode()
                                    {
                                        return Meters.GetHashCode();
                                    }

                                    /// <summary>
                                    ///     Equality operator.
                                    /// </summary>
                                    public static global::System.Boolean operator ==(Length left, Length right)
                                    {
                                        return left.Equals(right);
                                    }

                                    /// <summary>
                                    ///     Inequality operator.
                                    /// </summary>
                                    public static global::System.Boolean operator !=(Length left, Length right)
                                    {
                                        return !left.Equals(right);
                                    }
                                
                                    /// <summary>
                                    ///     Greater-than operator.
                                    /// </summary>
                                    public static global::System.Boolean operator >(Length left, Length right)
                                    {
                                        return left.Meters > right.Meters;
                                    }
                                
                                    /// <summary>
                                    ///     Less-than operator.
                                    /// </summary>
                                    public static global::System.Boolean operator <(Length left, Length right)
                                    {
                                        return left.Meters < right.Meters;
                                    }
                                
                                    /// <summary>
                                    ///     Greater-than-or-equal operator.
                                    /// </summary>
                                    public static global::System.Boolean operator >=(Length left, Length right)
                                    {
                                        return left.Meters >= right.Meters;
                                    }
                                
                                    /// <summary>
                                    ///     Less-than-or-equal operator.
                                    /// </summary>
                                    public static global::System.Boolean operator <=(Length left, Length right)
                                    {
                                        return left.Meters <= right.Meters;
                                    }

                                    /// <inheritdoc />
                                    public override global::System.String ToString()
                                    {
                                        return ToString(format: null);
                                    }
                                
                                    /// <summary>
                                    ///     Convert the measure to a string.
                                    /// </summary>
                                    /// <param name="format">The format provider.</param>
                                    /// <returns>The string representation of the measure.</returns>
                                    public global::System.String ToString(global::System.IFormatProvider? format)
                                    {
                                        return global::VoxelGame.Core.Utilities.Units.IMeasure.ToString(this, format);
                                    }
                                }

                                """;

        Assert.Equal(expected, RunGenerator(source),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }
}
