// <copyright file="ValueSemanticsGeneratorTests.cs" company="VoxelGame">
//     VoxelGame - a voxel-based video game.
//     Copyright (C) 2026 Jean Patrick Mathes
//      
//     This program is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//     
//     This program is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
//     
//     You should have received a copy of the GNU General Public License
//     along with this program.  If not, see <https://www.gnu.org/licenses/>.
// </copyright>
// <author>jeanpmathes</author>

using System;
using VoxelGame.Annotations.Attributes;
using VoxelGame.SourceGenerators.Generators;
using VoxelGame.SourceGenerators.Tests.Utilities;
using Xunit;

namespace VoxelGame.SourceGenerators.Tests.Generators;

public class ValueSemanticsGeneratorTests
{
    private static String RunGenerator(String source)
    {
        return TestTools.RunGenerator<ValueSemanticsGenerator>(source, "_ValueSemantics.g.cs", typeof(GenerateRecordAttribute));
    }

    [Fact]
    public void ValueSemanticsGenerator_ShouldGenerateTheSemantics()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations.Attributes;

                               namespace TestNamespace;

                               [ValueSemantics]
                               public struct TestStruct
                               {
                                   public Int32 X;
                                   public String Text;
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by ValueSemanticsGenerator

                               #nullable enable

                               namespace TestNamespace;

                               public partial struct TestStruct : global::System.IEquatable<TestStruct>, global::VoxelGame.Toolkit.Utilities.IDefault<TestStruct>
                               {
                                   /// <inheritdoc />
                                   public static TestStruct Default => new();

                                   private (global::System.Int32, global::System.String) Pack => (X, Text);

                                   /// <inheritdoc />
                                   public override global::System.Boolean Equals(global::System.Object? obj)
                                   {
                                       return obj is TestStruct other && Equals(other);
                                   }

                                   /// <inheritdoc />
                                   public global::System.Boolean Equals(TestStruct other)
                                   {
                                       return Pack.Equals(other.Pack);
                                   }

                                   /// <inheritdoc />
                                   public override global::System.Int32 GetHashCode()
                                   {
                                       return Pack.GetHashCode();
                                   }

                                   /// <summary>
                                   ///     Equality operator.
                                   /// </summary>
                                   public static global::System.Boolean operator ==(TestStruct left, TestStruct right) => left.Equals(right);

                                   /// <summary>
                                   ///     Inequality operator.
                                   /// </summary>
                                   public static global::System.Boolean operator !=(TestStruct left, TestStruct right) => !(left == right);
                               }

                               """;

        Assert.Equal(newText,
            RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void ValueSemanticsGenerator_ShouldGenerateTheSemanticsForZeroFields()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations.Attributes;

                               namespace TestNamespace;

                               [ValueSemantics]
                               public struct TestStruct
                               {
                                   
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by ValueSemanticsGenerator

                               #nullable enable

                               namespace TestNamespace;

                               public partial struct TestStruct : global::System.IEquatable<TestStruct>, global::VoxelGame.Toolkit.Utilities.IDefault<TestStruct>
                               {
                                   /// <inheritdoc />
                                   public static TestStruct Default => new();

                                   private global::System.ValueTuple Pack => global::System.ValueTuple.Create();

                                   /// <inheritdoc />
                                   public override global::System.Boolean Equals(global::System.Object? obj)
                                   {
                                       return obj is TestStruct other && Equals(other);
                                   }

                                   /// <inheritdoc />
                                   public global::System.Boolean Equals(TestStruct other)
                                   {
                                       return Pack.Equals(other.Pack);
                                   }

                                   /// <inheritdoc />
                                   public override global::System.Int32 GetHashCode()
                                   {
                                       return Pack.GetHashCode();
                                   }

                                   /// <summary>
                                   ///     Equality operator.
                                   /// </summary>
                                   public static global::System.Boolean operator ==(TestStruct left, TestStruct right) => left.Equals(right);

                                   /// <summary>
                                   ///     Inequality operator.
                                   /// </summary>
                                   public static global::System.Boolean operator !=(TestStruct left, TestStruct right) => !(left == right);
                               }

                               """;

        Assert.Equal(newText,
            RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }

    [Fact]
    public void ValueSemanticsGenerator_ShouldGenerateTheSemanticsForOneField()
    {
        const String oldText = """
                               using System;
                               using VoxelGame.Annotations.Attributes;

                               namespace TestNamespace;

                               [ValueSemantics]
                               public struct TestStruct
                               {
                                   public Int32 X;
                               }
                               """;

        const String newText = """
                               // <auto-generated />
                               // by ValueSemanticsGenerator

                               #nullable enable

                               namespace TestNamespace;

                               public partial struct TestStruct : global::System.IEquatable<TestStruct>, global::VoxelGame.Toolkit.Utilities.IDefault<TestStruct>
                               {
                                   /// <inheritdoc />
                                   public static TestStruct Default => new();

                                   private global::System.ValueTuple<global::System.Int32> Pack => global::System.ValueTuple.Create(X);

                                   /// <inheritdoc />
                                   public override global::System.Boolean Equals(global::System.Object? obj)
                                   {
                                       return obj is TestStruct other && Equals(other);
                                   }

                                   /// <inheritdoc />
                                   public global::System.Boolean Equals(TestStruct other)
                                   {
                                       return Pack.Equals(other.Pack);
                                   }

                                   /// <inheritdoc />
                                   public override global::System.Int32 GetHashCode()
                                   {
                                       return Pack.GetHashCode();
                                   }

                                   /// <summary>
                                   ///     Equality operator.
                                   /// </summary>
                                   public static global::System.Boolean operator ==(TestStruct left, TestStruct right) => left.Equals(right);

                                   /// <summary>
                                   ///     Inequality operator.
                                   /// </summary>
                                   public static global::System.Boolean operator !=(TestStruct left, TestStruct right) => !(left == right);
                               }

                               """;

        Assert.Equal(newText,
            RunGenerator(oldText),
            ignoreLineEndingDifferences: true,
            ignoreWhiteSpaceDifferences: true);
    }
}
