//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoxelGame.Core.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VoxelGame.Core.Resources.Language.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air.
        /// </summary>
        public static string Air {
            get {
                return ResourceManager.GetString("Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ash.
        /// </summary>
        public static string Ash {
            get {
                return ResourceManager.GetString("Ash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ash-covered Dirt.
        /// </summary>
        public static string AshCoveredDirt {
            get {
                return ResourceManager.GetString("AshCoveredDirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrier.
        /// </summary>
        public static string Barrier {
            get {
                return ResourceManager.GetString("Barrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bars.
        /// </summary>
        public static string Bars {
            get {
                return ResourceManager.GetString("Bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed.
        /// </summary>
        public static string Bed {
            get {
                return ResourceManager.GetString("Bed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beer.
        /// </summary>
        public static string Beer {
            get {
                return ResourceManager.GetString("Beer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bricks.
        /// </summary>
        public static string Bricks {
            get {
                return ResourceManager.GetString("Bricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick Wall.
        /// </summary>
        public static string BrickWall {
            get {
                return ResourceManager.GetString("BrickWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cactus.
        /// </summary>
        public static string Cactus {
            get {
                return ResourceManager.GetString("Cactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpet.
        /// </summary>
        public static string Carpet {
            get {
                return ResourceManager.GetString("Carpet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Checkerboard Tiles.
        /// </summary>
        public static string CheckerboardTilesBlack {
            get {
                return ResourceManager.GetString("CheckerboardTilesBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Checkerboard Tiles.
        /// </summary>
        public static string CheckerboardTilesWhite {
            get {
                return ResourceManager.GetString("CheckerboardTilesWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clay.
        /// </summary>
        public static string Clay {
            get {
                return ResourceManager.GetString("Clay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coal Ore.
        /// </summary>
        public static string CoalOre {
            get {
                return ResourceManager.GetString("CoalOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete.
        /// </summary>
        public static string Concrete {
            get {
                return ResourceManager.GetString("Concrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        public static string Core {
            get {
                return ResourceManager.GetString("Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New World.
        /// </summary>
        public static string CreateNewWorld {
            get {
                return ResourceManager.GetString("CreateNewWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosshair Color.
        /// </summary>
        public static string CrosshairColor {
            get {
                return ResourceManager.GetString("CrosshairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosshair Scale.
        /// </summary>
        public static string CrosshairScale {
            get {
                return ResourceManager.GetString("CrosshairScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crude Oil.
        /// </summary>
        public static string CrudeOil {
            get {
                return ResourceManager.GetString("CrudeOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorated Carpet.
        /// </summary>
        public static string DecoratedCarpet {
            get {
                return ResourceManager.GetString("DecoratedCarpet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorated Wool.
        /// </summary>
        public static string DecoratedWool {
            get {
                return ResourceManager.GetString("DecoratedWool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete World?.
        /// </summary>
        public static string DeleteWorldQuery {
            get {
                return ResourceManager.GetString("DeleteWorldQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirt.
        /// </summary>
        public static string Dirt {
            get {
                return ResourceManager.GetString("Dirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a world name.
        /// </summary>
        public static string EnterWorldName {
            get {
                return ResourceManager.GetString("EnterWorldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eternal Flame.
        /// </summary>
        public static string EternalFlame {
            get {
                return ResourceManager.GetString("EternalFlame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmland.
        /// </summary>
        public static string Farmland {
            get {
                return ResourceManager.GetString("Farmland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        public static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flax.
        /// </summary>
        public static string Flax {
            get {
                return ResourceManager.GetString("Flax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flower.
        /// </summary>
        public static string Flower {
            get {
                return ResourceManager.GetString("Flower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluid.
        /// </summary>
        public static string Fluid {
            get {
                return ResourceManager.GetString("Fluid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change general settings..
        /// </summary>
        public static string GeneralSettingsDescription {
            get {
                return ResourceManager.GetString("GeneralSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass.
        /// </summary>
        public static string Glass {
            get {
                return ResourceManager.GetString("Glass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass Pane.
        /// </summary>
        public static string GlassPane {
            get {
                return ResourceManager.GetString("GlassPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Ore.
        /// </summary>
        public static string GoldOre {
            get {
                return ResourceManager.GetString("GoldOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granite.
        /// </summary>
        public static string Granite {
            get {
                return ResourceManager.GetString("Granite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        public static string Graphics {
            get {
                return ResourceManager.GetString("Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anisotropic Filtering.
        /// </summary>
        public static string GraphicsAnisotropicFiltering {
            get {
                return ResourceManager.GetString("GraphicsAnisotropicFiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foliage Quality.
        /// </summary>
        public static string GraphicsFoliageQuality {
            get {
                return ResourceManager.GetString("GraphicsFoliageQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max FPS.
        /// </summary>
        public static string GraphicsMaxFPS {
            get {
                return ResourceManager.GetString("GraphicsMaxFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Count (MSAA).
        /// </summary>
        public static string GraphicsSampleCount {
            get {
                return ResourceManager.GetString("GraphicsSampleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set different graphics settings that can affect the quality of the game visuals. Some settings require a restart to apply..
        /// </summary>
        public static string GraphicsSettingsDescription {
            get {
                return ResourceManager.GetString("GraphicsSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use borderless (windowed) fullscreen.
        /// </summary>
        public static string GraphicsUseFullscreenBorderless {
            get {
                return ResourceManager.GetString("GraphicsUseFullscreenBorderless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grass.
        /// </summary>
        public static string Grass {
            get {
                return ResourceManager.GetString("Grass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravel.
        /// </summary>
        public static string Gravel {
            get {
                return ResourceManager.GetString("Gravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honey.
        /// </summary>
        public static string Honey {
            get {
                return ResourceManager.GetString("Honey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input not valid!.
        /// </summary>
        public static string InputNotValid {
            get {
                return ResourceManager.GetString("InputNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron Ore.
        /// </summary>
        public static string IronOre {
            get {
                return ResourceManager.GetString("IronOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backwards.
        /// </summary>
        public static string KeyBackwards {
            get {
                return ResourceManager.GetString("KeyBackwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybinds.
        /// </summary>
        public static string Keybinds {
            get {
                return ResourceManager.GetString("Keybinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind keys for different actions..
        /// </summary>
        public static string KeybindsSettingsDescription {
            get {
                return ResourceManager.GetString("KeybindsSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string KeyConsole {
            get {
                return ResourceManager.GetString("KeyConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crouch.
        /// </summary>
        public static string KeyCrouch {
            get {
                return ResourceManager.GetString("KeyCrouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug View.
        /// </summary>
        public static string KeyDebugView {
            get {
                return ResourceManager.GetString("KeyDebugView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy.
        /// </summary>
        public static string KeyDestroy {
            get {
                return ResourceManager.GetString("KeyDestroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape.
        /// </summary>
        public static string KeyEscape {
            get {
                return ResourceManager.GetString("KeyEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Interaction.
        /// </summary>
        public static string KeyForceInteract {
            get {
                return ResourceManager.GetString("KeyForceInteract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwards.
        /// </summary>
        public static string KeyForwards {
            get {
                return ResourceManager.GetString("KeyForwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string KeyFullscreen {
            get {
                return ResourceManager.GetString("KeyFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interact / Place.
        /// </summary>
        public static string KeyInteractOrPlace {
            get {
                return ResourceManager.GetString("KeyInteractOrPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        public static string KeyJump {
            get {
                return ResourceManager.GetString("KeyJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Placement.
        /// </summary>
        public static string KeyNextPlacement {
            get {
                return ResourceManager.GetString("KeyNextPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement Mode.
        /// </summary>
        public static string KeyPlacementMode {
            get {
                return ResourceManager.GetString("KeyPlacementMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Placement.
        /// </summary>
        public static string KeyPreviousPlacement {
            get {
                return ResourceManager.GetString("KeyPreviousPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        public static string KeyScreenshot {
            get {
                return ResourceManager.GetString("KeyScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Targeted.
        /// </summary>
        public static string KeySelectTargeted {
            get {
                return ResourceManager.GetString("KeySelectTargeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint.
        /// </summary>
        public static string KeySprint {
            get {
                return ResourceManager.GetString("KeySprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strafe Left.
        /// </summary>
        public static string KeyStrafeLeft {
            get {
                return ResourceManager.GetString("KeyStrafeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strafe Right.
        /// </summary>
        public static string KeyStrafeRight {
            get {
                return ResourceManager.GetString("KeyStrafeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle UI.
        /// </summary>
        public static string KeyToggleUI {
            get {
                return ResourceManager.GetString("KeyToggleUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireframe.
        /// </summary>
        public static string KeyWireframe {
            get {
                return ResourceManager.GetString("KeyWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladder.
        /// </summary>
        public static string Ladder {
            get {
                return ResourceManager.GetString("Ladder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Tiles.
        /// </summary>
        public static string LargeTiles {
            get {
                return ResourceManager.GetString("LargeTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lava.
        /// </summary>
        public static string Lava {
            get {
                return ResourceManager.GetString("Lava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves.
        /// </summary>
        public static string Leaves {
            get {
                return ResourceManager.GetString("Leaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limestone.
        /// </summary>
        public static string Limestone {
            get {
                return ResourceManager.GetString("Limestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maize.
        /// </summary>
        public static string Maize {
            get {
                return ResourceManager.GetString("Maize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marble.
        /// </summary>
        public static string Marble {
            get {
                return ResourceManager.GetString("Marble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melon.
        /// </summary>
        public static string Melon {
            get {
                return ResourceManager.GetString("Melon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melon Plant.
        /// </summary>
        public static string MelonPlant {
            get {
                return ResourceManager.GetString("MelonPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milk.
        /// </summary>
        public static string Milk {
            get {
                return ResourceManager.GetString("Milk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Sensitivity.
        /// </summary>
        public static string MouseSensitivity {
            get {
                return ResourceManager.GetString("MouseSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mud.
        /// </summary>
        public static string Mud {
            get {
                return ResourceManager.GetString("Mud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Gas.
        /// </summary>
        public static string NaturalGas {
            get {
                return ResourceManager.GetString("NaturalGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Fluid.
        /// </summary>
        public static string NoFluid {
            get {
                return ResourceManager.GetString("NoFluid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsidian.
        /// </summary>
        public static string Obsidian {
            get {
                return ResourceManager.GetString("Obsidian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onions.
        /// </summary>
        public static string Onions {
            get {
                return ResourceManager.GetString("Onions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paving Stone.
        /// </summary>
        public static string PavingStone {
            get {
                return ResourceManager.GetString("PavingStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol.
        /// </summary>
        public static string Petrol {
            get {
                return ResourceManager.GetString("Petrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potatoes.
        /// </summary>
        public static string Potatoes {
            get {
                return ResourceManager.GetString("Potatoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key or button....
        /// </summary>
        public static string PressAnyKeyOrButton {
            get {
                return ResourceManager.GetString("PressAnyKeyOrButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulsating Block.
        /// </summary>
        public static string PulsatingBlock {
            get {
                return ResourceManager.GetString("PulsatingBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumice.
        /// </summary>
        public static string Pumice {
            get {
                return ResourceManager.GetString("Pumice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pump.
        /// </summary>
        public static string Pump {
            get {
                return ResourceManager.GetString("Pump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumpkin.
        /// </summary>
        public static string Pumpkin {
            get {
                return ResourceManager.GetString("Pumpkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumpkin Plant.
        /// </summary>
        public static string PumpkinPlant {
            get {
                return ResourceManager.GetString("PumpkinPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Plastic.
        /// </summary>
        public static string RedPlastic {
            get {
                return ResourceManager.GetString("RedPlastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubble.
        /// </summary>
        public static string Rubble {
            get {
                return ResourceManager.GetString("Rubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubble Wall.
        /// </summary>
        public static string RubbleWall {
            get {
                return ResourceManager.GetString("RubbleWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sand.
        /// </summary>
        public static string Sand {
            get {
                return ResourceManager.GetString("Sand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandstone.
        /// </summary>
        public static string Sandstone {
            get {
                return ResourceManager.GetString("Sandstone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Tiles.
        /// </summary>
        public static string SmallTiles {
            get {
                return ResourceManager.GetString("SmallTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        public static string Snow {
            get {
                return ResourceManager.GetString("Snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spider Web.
        /// </summary>
        public static string SpiderWeb {
            get {
                return ResourceManager.GetString("SpiderWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam.
        /// </summary>
        public static string Steam {
            get {
                return ResourceManager.GetString("Steam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel.
        /// </summary>
        public static string Steel {
            get {
                return ResourceManager.GetString("Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel Door.
        /// </summary>
        public static string SteelDoor {
            get {
                return ResourceManager.GetString("SteelDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel Pipe.
        /// </summary>
        public static string SteelPipe {
            get {
                return ResourceManager.GetString("SteelPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Steelpipe.
        /// </summary>
        public static string SteelPipeStraight {
            get {
                return ResourceManager.GetString("SteelPipeStraight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone Face.
        /// </summary>
        public static string StoneFace {
            get {
                return ResourceManager.GetString("StoneFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tall Flower.
        /// </summary>
        public static string TallFlower {
            get {
                return ResourceManager.GetString("TallFlower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tall Grass.
        /// </summary>
        public static string TallGrass {
            get {
                return ResourceManager.GetString("TallGrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiled Glass.
        /// </summary>
        public static string TiledGlass {
            get {
                return ResourceManager.GetString("TiledGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve Pipe.
        /// </summary>
        public static string ValvePipe {
            get {
                return ResourceManager.GetString("ValvePipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vase.
        /// </summary>
        public static string Vase {
            get {
                return ResourceManager.GetString("Vase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Tall Grass.
        /// </summary>
        public static string VeryTallGrass {
            get {
                return ResourceManager.GetString("VeryTallGrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vines.
        /// </summary>
        public static string Vines {
            get {
                return ResourceManager.GetString("Vines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoxelGame.
        /// </summary>
        public static string VoxelGame {
            get {
                return ResourceManager.GetString("VoxelGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheat.
        /// </summary>
        public static string Wheat {
            get {
                return ResourceManager.GetString("Wheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wine.
        /// </summary>
        public static string Wine {
            get {
                return ResourceManager.GetString("Wine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood.
        /// </summary>
        public static string Wood {
            get {
                return ResourceManager.GetString("Wood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wooden Door.
        /// </summary>
        public static string WoodenDoor {
            get {
                return ResourceManager.GetString("WoodenDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wooden Fence.
        /// </summary>
        public static string WoodenFence {
            get {
                return ResourceManager.GetString("WoodenFence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wooden Gate.
        /// </summary>
        public static string WoodenGate {
            get {
                return ResourceManager.GetString("WoodenGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wooden Pipe.
        /// </summary>
        public static string WoodenPipe {
            get {
                return ResourceManager.GetString("WoodenPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wool.
        /// </summary>
        public static string Wool {
            get {
                return ResourceManager.GetString("Wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked Stone.
        /// </summary>
        public static string WorkedStone {
            get {
                return ResourceManager.GetString("WorkedStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worlds.
        /// </summary>
        public static string Worlds {
            get {
                return ResourceManager.GetString("Worlds", resourceCulture);
            }
        }
    }
}
