//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoxelGame.Core.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VoxelGame.Core.Resources.Language.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air.
        /// </summary>
        public static string Air {
            get {
                return ResourceManager.GetString("Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ash.
        /// </summary>
        public static string Ash {
            get {
                return ResourceManager.GetString("Ash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ash-covered Dirt.
        /// </summary>
        public static string AshCoveredDirt {
            get {
                return ResourceManager.GetString("AshCoveredDirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrier.
        /// </summary>
        public static string Barrier {
            get {
                return ResourceManager.GetString("Barrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bars.
        /// </summary>
        public static string Bars {
            get {
                return ResourceManager.GetString("Bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed.
        /// </summary>
        public static string Bed {
            get {
                return ResourceManager.GetString("Bed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beer.
        /// </summary>
        public static string Beer {
            get {
                return ResourceManager.GetString("Beer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cactus.
        /// </summary>
        public static string Cactus {
            get {
                return ResourceManager.GetString("Cactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpet.
        /// </summary>
        public static string Carpet {
            get {
                return ResourceManager.GetString("Carpet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorated Carpet.
        /// </summary>
        public static string CarpetDecorated {
            get {
                return ResourceManager.GetString("CarpetDecorated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Checkerboard Tiles.
        /// </summary>
        public static string CheckerboardTilesBlack {
            get {
                return ResourceManager.GetString("CheckerboardTilesBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Checkerboard Tiles.
        /// </summary>
        public static string CheckerboardTilesWhite {
            get {
                return ResourceManager.GetString("CheckerboardTilesWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clay.
        /// </summary>
        public static string Clay {
            get {
                return ResourceManager.GetString("Clay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clay Bricks.
        /// </summary>
        public static string ClayBricks {
            get {
                return ResourceManager.GetString("ClayBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clay Brick Wall.
        /// </summary>
        public static string ClayBrickWall {
            get {
                return ResourceManager.GetString("ClayBrickWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearInput {
            get {
                return ResourceManager.GetString("ClearInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coal Ore.
        /// </summary>
        public static string CoalOre {
            get {
                return ResourceManager.GetString("CoalOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete.
        /// </summary>
        public static string Concrete {
            get {
                return ResourceManager.GetString("Concrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        public static string Core {
            get {
                return ResourceManager.GetString("Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on.
        /// </summary>
        public static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New World.
        /// </summary>
        public static string CreateNewWorld {
            get {
                return ResourceManager.GetString("CreateNewWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosshair Color.
        /// </summary>
        public static string CrosshairColor {
            get {
                return ResourceManager.GetString("CrosshairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosshair Scale.
        /// </summary>
        public static string CrosshairScale {
            get {
                return ResourceManager.GetString("CrosshairScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crude Oil.
        /// </summary>
        public static string CrudeOil {
            get {
                return ResourceManager.GetString("CrudeOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete world?.
        /// </summary>
        public static string DeleteWorldQuery {
            get {
                return ResourceManager.GetString("DeleteWorldQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirt.
        /// </summary>
        public static string Dirt {
            get {
                return ResourceManager.GetString("Dirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a world name.
        /// </summary>
        public static string EnterWorldName {
            get {
                return ResourceManager.GetString("EnterWorldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eternal Flame.
        /// </summary>
        public static string EternalFlame {
            get {
                return ResourceManager.GetString("EternalFlame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit to OS.
        /// </summary>
        public static string ExitToOS {
            get {
                return ResourceManager.GetString("ExitToOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmland.
        /// </summary>
        public static string Farmland {
            get {
                return ResourceManager.GetString("Farmland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        public static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flax.
        /// </summary>
        public static string Flax {
            get {
                return ResourceManager.GetString("Flax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flower.
        /// </summary>
        public static string Flower {
            get {
                return ResourceManager.GetString("Flower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluid.
        /// </summary>
        public static string Fluid {
            get {
                return ResourceManager.GetString("Fluid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh Water.
        /// </summary>
        public static string FreshWater {
            get {
                return ResourceManager.GetString("FreshWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change general settings..
        /// </summary>
        public static string GeneralSettingsDescription {
            get {
                return ResourceManager.GetString("GeneralSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass.
        /// </summary>
        public static string Glass {
            get {
                return ResourceManager.GetString("Glass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass Pane.
        /// </summary>
        public static string GlassPane {
            get {
                return ResourceManager.GetString("GlassPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Ore.
        /// </summary>
        public static string GoldOre {
            get {
                return ResourceManager.GetString("GoldOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granite.
        /// </summary>
        public static string Granite {
            get {
                return ResourceManager.GetString("Granite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granite Bricks.
        /// </summary>
        public static string GraniteBricks {
            get {
                return ResourceManager.GetString("GraniteBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granite Brick Wall.
        /// </summary>
        public static string GraniteBrickWall {
            get {
                return ResourceManager.GetString("GraniteBrickWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granite Cobbles.
        /// </summary>
        public static string GraniteCobbles {
            get {
                return ResourceManager.GetString("GraniteCobbles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granite Column.
        /// </summary>
        public static string GraniteColumn {
            get {
                return ResourceManager.GetString("GraniteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorated Granite.
        /// </summary>
        public static string GraniteDecorated {
            get {
                return ResourceManager.GetString("GraniteDecorated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granite Paving.
        /// </summary>
        public static string GranitePaving {
            get {
                return ResourceManager.GetString("GranitePaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granite Rubble.
        /// </summary>
        public static string GraniteRubble {
            get {
                return ResourceManager.GetString("GraniteRubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granite Wall.
        /// </summary>
        public static string GraniteWall {
            get {
                return ResourceManager.GetString("GraniteWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked Granite.
        /// </summary>
        public static string GraniteWorked {
            get {
                return ResourceManager.GetString("GraniteWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        public static string Graphics {
            get {
                return ResourceManager.GetString("Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anisotropic Filtering.
        /// </summary>
        public static string GraphicsAnisotropicFiltering {
            get {
                return ResourceManager.GetString("GraphicsAnisotropicFiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foliage Quality.
        /// </summary>
        public static string GraphicsFoliageQuality {
            get {
                return ResourceManager.GetString("GraphicsFoliageQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering Resolution Scale.
        /// </summary>
        public static string GraphicsRenderResolutionScale {
            get {
                return ResourceManager.GetString("GraphicsRenderResolutionScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set different graphics settings that can affect the quality of the game visuals. Some settings require a restart to apply..
        /// </summary>
        public static string GraphicsSettingsDescription {
            get {
                return ResourceManager.GetString("GraphicsSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Size.
        /// </summary>
        public static string GraphicsWindowSize {
            get {
                return ResourceManager.GetString("GraphicsWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grass.
        /// </summary>
        public static string Grass {
            get {
                return ResourceManager.GetString("Grass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravel.
        /// </summary>
        public static string Gravel {
            get {
                return ResourceManager.GetString("Gravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honey.
        /// </summary>
        public static string Honey {
            get {
                return ResourceManager.GetString("Honey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice.
        /// </summary>
        public static string Ice {
            get {
                return ResourceManager.GetString("Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input not valid!.
        /// </summary>
        public static string InputNotValid {
            get {
                return ResourceManager.GetString("InputNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron Ore.
        /// </summary>
        public static string IronOre {
            get {
                return ResourceManager.GetString("IronOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backwards.
        /// </summary>
        public static string KeyBackwards {
            get {
                return ResourceManager.GetString("KeyBackwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybinds.
        /// </summary>
        public static string Keybinds {
            get {
                return ResourceManager.GetString("Keybinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind keys for different actions..
        /// </summary>
        public static string KeybindsSettingsDescription {
            get {
                return ResourceManager.GetString("KeybindsSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string KeyConsole {
            get {
                return ResourceManager.GetString("KeyConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crouch.
        /// </summary>
        public static string KeyCrouch {
            get {
                return ResourceManager.GetString("KeyCrouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug View.
        /// </summary>
        public static string KeyDebugView {
            get {
                return ResourceManager.GetString("KeyDebugView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy.
        /// </summary>
        public static string KeyDestroy {
            get {
                return ResourceManager.GetString("KeyDestroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape.
        /// </summary>
        public static string KeyEscape {
            get {
                return ResourceManager.GetString("KeyEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Interaction.
        /// </summary>
        public static string KeyForceInteract {
            get {
                return ResourceManager.GetString("KeyForceInteract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwards.
        /// </summary>
        public static string KeyForwards {
            get {
                return ResourceManager.GetString("KeyForwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string KeyFullscreen {
            get {
                return ResourceManager.GetString("KeyFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interact / Place.
        /// </summary>
        public static string KeyInteractOrPlace {
            get {
                return ResourceManager.GetString("KeyInteractOrPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        public static string KeyJump {
            get {
                return ResourceManager.GetString("KeyJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Placement.
        /// </summary>
        public static string KeyNextPlacement {
            get {
                return ResourceManager.GetString("KeyNextPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement Mode.
        /// </summary>
        public static string KeyPlacementMode {
            get {
                return ResourceManager.GetString("KeyPlacementMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Placement.
        /// </summary>
        public static string KeyPreviousPlacement {
            get {
                return ResourceManager.GetString("KeyPreviousPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        public static string KeyScreenshot {
            get {
                return ResourceManager.GetString("KeyScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Targeted.
        /// </summary>
        public static string KeySelectTargeted {
            get {
                return ResourceManager.GetString("KeySelectTargeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint.
        /// </summary>
        public static string KeySprint {
            get {
                return ResourceManager.GetString("KeySprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strafe Left.
        /// </summary>
        public static string KeyStrafeLeft {
            get {
                return ResourceManager.GetString("KeyStrafeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strafe Right.
        /// </summary>
        public static string KeyStrafeRight {
            get {
                return ResourceManager.GetString("KeyStrafeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle UI.
        /// </summary>
        public static string KeyToggleUI {
            get {
                return ResourceManager.GetString("KeyToggleUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Mouse.
        /// </summary>
        public static string KeyUnlockMouse {
            get {
                return ResourceManager.GetString("KeyUnlockMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireframe.
        /// </summary>
        public static string KeyWireframe {
            get {
                return ResourceManager.GetString("KeyWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladder.
        /// </summary>
        public static string Ladder {
            get {
                return ResourceManager.GetString("Ladder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Tiles.
        /// </summary>
        public static string LargeTiles {
            get {
                return ResourceManager.GetString("LargeTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last loaded.
        /// </summary>
        public static string LastLoaded {
            get {
                return ResourceManager.GetString("LastLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lava.
        /// </summary>
        public static string Lava {
            get {
                return ResourceManager.GetString("Lava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves.
        /// </summary>
        public static string Leaves {
            get {
                return ResourceManager.GetString("Leaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limestone.
        /// </summary>
        public static string Limestone {
            get {
                return ResourceManager.GetString("Limestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limestone Bricks.
        /// </summary>
        public static string LimestoneBricks {
            get {
                return ResourceManager.GetString("LimestoneBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limestone Brick Wall.
        /// </summary>
        public static string LimestoneBrickWall {
            get {
                return ResourceManager.GetString("LimestoneBrickWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limestone Cobbles.
        /// </summary>
        public static string LimestoneCobbles {
            get {
                return ResourceManager.GetString("LimestoneCobbles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limestone Column.
        /// </summary>
        public static string LimestoneColumn {
            get {
                return ResourceManager.GetString("LimestoneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorated Limestone.
        /// </summary>
        public static string LimestoneDecorated {
            get {
                return ResourceManager.GetString("LimestoneDecorated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limestone Paving.
        /// </summary>
        public static string LimestonePaving {
            get {
                return ResourceManager.GetString("LimestonePaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limestone Rubble.
        /// </summary>
        public static string LimestoneRubble {
            get {
                return ResourceManager.GetString("LimestoneRubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limestone Wall.
        /// </summary>
        public static string LimestoneWall {
            get {
                return ResourceManager.GetString("LimestoneWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked Limestone.
        /// </summary>
        public static string LimestoneWorked {
            get {
                return ResourceManager.GetString("LimestoneWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maize.
        /// </summary>
        public static string Maize {
            get {
                return ResourceManager.GetString("Maize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marble.
        /// </summary>
        public static string Marble {
            get {
                return ResourceManager.GetString("Marble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marble Bricks.
        /// </summary>
        public static string MarbleBricks {
            get {
                return ResourceManager.GetString("MarbleBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marble Brick Wall.
        /// </summary>
        public static string MarbleBrickWall {
            get {
                return ResourceManager.GetString("MarbleBrickWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marble Cobbles.
        /// </summary>
        public static string MarbleCobbles {
            get {
                return ResourceManager.GetString("MarbleCobbles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marble Column.
        /// </summary>
        public static string MarbleColumn {
            get {
                return ResourceManager.GetString("MarbleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorated Marble.
        /// </summary>
        public static string MarbleDecorated {
            get {
                return ResourceManager.GetString("MarbleDecorated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marble Paving.
        /// </summary>
        public static string MarblePaving {
            get {
                return ResourceManager.GetString("MarblePaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marble Rubble.
        /// </summary>
        public static string MarbleRubble {
            get {
                return ResourceManager.GetString("MarbleRubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marble Wall.
        /// </summary>
        public static string MarbleWall {
            get {
                return ResourceManager.GetString("MarbleWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked Marble.
        /// </summary>
        public static string MarbleWorked {
            get {
                return ResourceManager.GetString("MarbleWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melon.
        /// </summary>
        public static string Melon {
            get {
                return ResourceManager.GetString("Melon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melon Plant.
        /// </summary>
        public static string MelonPlant {
            get {
                return ResourceManager.GetString("MelonPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milk.
        /// </summary>
        public static string Milk {
            get {
                return ResourceManager.GetString("Milk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Resources.
        /// </summary>
        public static string MissingResources {
            get {
                return ResourceManager.GetString("MissingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Sensitivity.
        /// </summary>
        public static string MouseSensitivity {
            get {
                return ResourceManager.GetString("MouseSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mud.
        /// </summary>
        public static string Mud {
            get {
                return ResourceManager.GetString("Mud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Gas.
        /// </summary>
        public static string NaturalGas {
            get {
                return ResourceManager.GetString("NaturalGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Fluid.
        /// </summary>
        public static string NoFluid {
            get {
                return ResourceManager.GetString("NoFluid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found no worlds..
        /// </summary>
        public static string NoWorldsFound {
            get {
                return ResourceManager.GetString("NoWorldsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsidian.
        /// </summary>
        public static string Obsidian {
            get {
                return ResourceManager.GetString("Obsidian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsidian Bricks.
        /// </summary>
        public static string ObsidianBricks {
            get {
                return ResourceManager.GetString("ObsidianBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsidian Brick Wall.
        /// </summary>
        public static string ObsidianBrickWall {
            get {
                return ResourceManager.GetString("ObsidianBrickWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsidian Cobbles.
        /// </summary>
        public static string ObsidianCobbles {
            get {
                return ResourceManager.GetString("ObsidianCobbles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsidian Column.
        /// </summary>
        public static string ObsidianColumn {
            get {
                return ResourceManager.GetString("ObsidianColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorated Obsidian.
        /// </summary>
        public static string ObsidianDecorated {
            get {
                return ResourceManager.GetString("ObsidianDecorated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsidian Paving.
        /// </summary>
        public static string ObsidianPaving {
            get {
                return ResourceManager.GetString("ObsidianPaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsidian Rubble.
        /// </summary>
        public static string ObsidianRubble {
            get {
                return ResourceManager.GetString("ObsidianRubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsidian Wall.
        /// </summary>
        public static string ObsidianWall {
            get {
                return ResourceManager.GetString("ObsidianWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked Obsidian.
        /// </summary>
        public static string ObsidianWorked {
            get {
                return ResourceManager.GetString("ObsidianWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onions.
        /// </summary>
        public static string Onions {
            get {
                return ResourceManager.GetString("Onions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Directory.
        /// </summary>
        public static string OpenDirectory {
            get {
                return ResourceManager.GetString("OpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string OperationStatusError {
            get {
                return ResourceManager.GetString("OperationStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string OperationStatusOk {
            get {
                return ResourceManager.GetString("OperationStatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string OperationStatusRunning {
            get {
                return ResourceManager.GetString("OperationStatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permafrost.
        /// </summary>
        public static string Permafrost {
            get {
                return ResourceManager.GetString("Permafrost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol.
        /// </summary>
        public static string Petrol {
            get {
                return ResourceManager.GetString("Petrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potatoes.
        /// </summary>
        public static string Potatoes {
            get {
                return ResourceManager.GetString("Potatoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key or button....
        /// </summary>
        public static string PressAnyKeyOrButton {
            get {
                return ResourceManager.GetString("PressAnyKeyOrButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulsating Block.
        /// </summary>
        public static string PulsatingBlock {
            get {
                return ResourceManager.GetString("PulsatingBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumice.
        /// </summary>
        public static string Pumice {
            get {
                return ResourceManager.GetString("Pumice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumice Bricks.
        /// </summary>
        public static string PumiceBricks {
            get {
                return ResourceManager.GetString("PumiceBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumice Brick Wall.
        /// </summary>
        public static string PumiceBrickWall {
            get {
                return ResourceManager.GetString("PumiceBrickWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumice Cobbles.
        /// </summary>
        public static string PumiceCobbles {
            get {
                return ResourceManager.GetString("PumiceCobbles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumice Column.
        /// </summary>
        public static string PumiceColumn {
            get {
                return ResourceManager.GetString("PumiceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorated Pumice.
        /// </summary>
        public static string PumiceDecorated {
            get {
                return ResourceManager.GetString("PumiceDecorated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumice Paving.
        /// </summary>
        public static string PumicePaving {
            get {
                return ResourceManager.GetString("PumicePaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumice Rubble.
        /// </summary>
        public static string PumiceRubble {
            get {
                return ResourceManager.GetString("PumiceRubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumice Wall.
        /// </summary>
        public static string PumiceWall {
            get {
                return ResourceManager.GetString("PumiceWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked Pumice.
        /// </summary>
        public static string PumiceWorked {
            get {
                return ResourceManager.GetString("PumiceWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pump.
        /// </summary>
        public static string Pump {
            get {
                return ResourceManager.GetString("Pump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumpkin.
        /// </summary>
        public static string Pumpkin {
            get {
                return ResourceManager.GetString("Pumpkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumpkin Plant.
        /// </summary>
        public static string PumpkinPlant {
            get {
                return ResourceManager.GetString("PumpkinPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Plastic.
        /// </summary>
        public static string RedPlastic {
            get {
                return ResourceManager.GetString("RedPlastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roots.
        /// </summary>
        public static string Roots {
            get {
                return ResourceManager.GetString("Roots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salt.
        /// </summary>
        public static string Salt {
            get {
                return ResourceManager.GetString("Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sand.
        /// </summary>
        public static string Sand {
            get {
                return ResourceManager.GetString("Sand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandstone.
        /// </summary>
        public static string Sandstone {
            get {
                return ResourceManager.GetString("Sandstone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandstone Bricks.
        /// </summary>
        public static string SandstoneBricks {
            get {
                return ResourceManager.GetString("SandstoneBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandstone Brick Wall.
        /// </summary>
        public static string SandstoneBrickWall {
            get {
                return ResourceManager.GetString("SandstoneBrickWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandstone Cobbles.
        /// </summary>
        public static string SandstoneCobbles {
            get {
                return ResourceManager.GetString("SandstoneCobbles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandstone Column.
        /// </summary>
        public static string SandstoneColumn {
            get {
                return ResourceManager.GetString("SandstoneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorated Sandstone.
        /// </summary>
        public static string SandstoneDecorated {
            get {
                return ResourceManager.GetString("SandstoneDecorated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandstone Paving.
        /// </summary>
        public static string SandstonePaving {
            get {
                return ResourceManager.GetString("SandstonePaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandstone Rubble.
        /// </summary>
        public static string SandstoneRubble {
            get {
                return ResourceManager.GetString("SandstoneRubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandstone Wall.
        /// </summary>
        public static string SandstoneWall {
            get {
                return ResourceManager.GetString("SandstoneWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked Sandstone.
        /// </summary>
        public static string SandstoneWorked {
            get {
                return ResourceManager.GetString("SandstoneWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale of UI.
        /// </summary>
        public static string ScaleOfUI {
            get {
                return ResourceManager.GetString("ScaleOfUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching worlds.
        /// </summary>
        public static string SearchingWorlds {
            get {
                return ResourceManager.GetString("SearchingWorlds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea Water.
        /// </summary>
        public static string SeaWater {
            get {
                return ResourceManager.GetString("SeaWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed.
        /// </summary>
        public static string Seed {
            get {
                return ResourceManager.GetString("Seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright Color of Selection.
        /// </summary>
        public static string SelectionBoxBrightColor {
            get {
                return ResourceManager.GetString("SelectionBoxBrightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Color of Selection.
        /// </summary>
        public static string SelectionBoxDarkColor {
            get {
                return ResourceManager.GetString("SelectionBoxDarkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string SizeBy {
            get {
                return ResourceManager.GetString("SizeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Tiles.
        /// </summary>
        public static string SmallTiles {
            get {
                return ResourceManager.GetString("SmallTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        public static string Snow {
            get {
                return ResourceManager.GetString("Snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spider Web.
        /// </summary>
        public static string SpiderWeb {
            get {
                return ResourceManager.GetString("SpiderWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam.
        /// </summary>
        public static string Steam {
            get {
                return ResourceManager.GetString("Steam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel.
        /// </summary>
        public static string Steel {
            get {
                return ResourceManager.GetString("Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel Door.
        /// </summary>
        public static string SteelDoor {
            get {
                return ResourceManager.GetString("SteelDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel Pipe.
        /// </summary>
        public static string SteelPipe {
            get {
                return ResourceManager.GetString("SteelPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Steelpipe.
        /// </summary>
        public static string SteelPipeStraight {
            get {
                return ResourceManager.GetString("SteelPipeStraight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tall Flower.
        /// </summary>
        public static string TallFlower {
            get {
                return ResourceManager.GetString("TallFlower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tall Grass.
        /// </summary>
        public static string TallGrass {
            get {
                return ResourceManager.GetString("TallGrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiled Glass.
        /// </summary>
        public static string TiledGlass {
            get {
                return ResourceManager.GetString("TiledGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string TimeSinceEventDays {
            get {
                return ResourceManager.GetString("TimeSinceEventDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ages ago.
        /// </summary>
        public static string TimeSinceEventEternity {
            get {
                return ResourceManager.GetString("TimeSinceEventEternity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string TimeSinceEventHours {
            get {
                return ResourceManager.GetString("TimeSinceEventHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string TimeSinceEventMinutes {
            get {
                return ResourceManager.GetString("TimeSinceEventMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just a moment ago.
        /// </summary>
        public static string TimeSinceEventMomentAgo {
            get {
                return ResourceManager.GetString("TimeSinceEventMomentAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to never.
        /// </summary>
        public static string TimeSinceEventNever {
            get {
                return ResourceManager.GetString("TimeSinceEventNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} weeks ago.
        /// </summary>
        public static string TimeSinceEventWeeks {
            get {
                return ResourceManager.GetString("TimeSinceEventWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve Pipe.
        /// </summary>
        public static string ValvePipe {
            get {
                return ResourceManager.GetString("ValvePipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vase.
        /// </summary>
        public static string Vase {
            get {
                return ResourceManager.GetString("Vase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Tall Grass.
        /// </summary>
        public static string VeryTallGrass {
            get {
                return ResourceManager.GetString("VeryTallGrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vines.
        /// </summary>
        public static string Vines {
            get {
                return ResourceManager.GetString("Vines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoxelGame.
        /// </summary>
        public static string VoxelGame {
            get {
                return ResourceManager.GetString("VoxelGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheat.
        /// </summary>
        public static string Wheat {
            get {
                return ResourceManager.GetString("Wheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wine.
        /// </summary>
        public static string Wine {
            get {
                return ResourceManager.GetString("Wine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood.
        /// </summary>
        public static string Wood {
            get {
                return ResourceManager.GetString("Wood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wooden Door.
        /// </summary>
        public static string WoodenDoor {
            get {
                return ResourceManager.GetString("WoodenDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wooden Fence.
        /// </summary>
        public static string WoodenFence {
            get {
                return ResourceManager.GetString("WoodenFence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wooden Gate.
        /// </summary>
        public static string WoodenGate {
            get {
                return ResourceManager.GetString("WoodenGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wooden Pipe.
        /// </summary>
        public static string WoodenPipe {
            get {
                return ResourceManager.GetString("WoodenPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wool.
        /// </summary>
        public static string Wool {
            get {
                return ResourceManager.GetString("Wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorated Wool.
        /// </summary>
        public static string WoolDecorated {
            get {
                return ResourceManager.GetString("WoolDecorated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worlds.
        /// </summary>
        public static string Worlds {
            get {
                return ResourceManager.GetString("Worlds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
