<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <LinkIncremental>false</LinkIncremental>
        <OutDir>bin\$(Platform)\$(Configuration)\</OutDir>
        <IntDir>obj\$(Platform)\$(Configuration)\</IntDir>
        <CopyCppRuntimeToOutputDir>true</CopyCppRuntimeToOutputDir>
        <RunCodeAnalysis>false</RunCodeAnalysis>
        <EnableClangTidyCodeAnalysis>false</EnableClangTidyCodeAnalysis>
    </PropertyGroup>
    <ItemDefinitionGroup>
        <ClCompile>
            <WarningLevel>Level4</WarningLevel>
            <PrecompiledHeader>Use</PrecompiledHeader>
            <Optimization>MaxSpeed</Optimization>
            <FunctionLevelLinking>true</FunctionLevelLinking>
            <PreprocessorDefinitions>WIN32;NDEBUG;_WINDOWS;%(PreprocessorDefinitions)</PreprocessorDefinitions>
            <SDLCheck>true</SDLCheck>
            <AdditionalIncludeDirectories>$(ProjectDir);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
            <CompileAsWinRT>false</CompileAsWinRT>
            <MultiProcessorCompilation>true</MultiProcessorCompilation>
            <LanguageStandard>stdcpp20</LanguageStandard>
            <IntrinsicFunctions>true</IntrinsicFunctions>
            <TreatWarningAsError>true</TreatWarningAsError>
        </ClCompile>
        <Link>
            <SubSystem>Windows</SubSystem>
            <EnableCOMDATFolding>true</EnableCOMDATFolding>
            <OptimizeReferences>true</OptimizeReferences>
        </Link>
    </ItemDefinitionGroup>
    <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
        <ClCompile>
            <PreprocessorDefinitions>NATIVE_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
            <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
        </ClCompile>
        <Link>
            <GenerateDebugInformation>true</GenerateDebugInformation>
        </Link>
    </ItemDefinitionGroup>
</Project>
