name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup coverage
      run: dotnet tool install --global dotnet-coverage
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache SonarCloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@v4
      with:
        path: .\.sonar\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner
    - name: Install SonarCloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        New-Item -Path .\.sonar\scanner -ItemType Directory
        dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
    - name: Install build wrapper
      shell: powershell
      run: |
        Invoke-WebRequest -Uri https://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip -OutFile build-wrapper-win.zip
        Expand-Archive -Force -Path build-wrapper-win.zip -DestinationPath .\.sonar\scanner\
        Remove-Item build-wrapper-win.zip
    - name: Restore dependencies
      run: msbuild -t:Restore -p:RestorePackagesConfig=true -p:Configuration=Release
    - name: Build, test and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: powershell
      run: |
        .\.sonar\scanner\dotnet-sonarscanner begin /k:"pershingthesecond_VoxelGame" /o:"pershingthesecond" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cfamily.build-wrapper-output=".\.sonar\build-wrapper-output" /d:sonar.cs.vscoveragexml.reportsPaths="coverage.xml"
        .\.sonar\scanner\build-wrapper-win-x86\build-wrapper-win-x86-64.exe --out-dir .\.sonar\build-wrapper-output exit 1 # msbuild -t:Build -p:RestorePackages=false -p:Configuration=Release
        dotnet-coverage collect "dotnet test -c Test --no-restore --no-build --verbosity normal" -f xml -o "coverage.xml" # Use dotnet because msbuild has problems with tests
        .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
